// Parses scripts/quiz/nba-500.raw.txt and emits a TypeScript module exporting
// the 500-question NBA bank as an array of `Quiz` objects, split into themed
// quizzes across the four NBA categories. Run: node scripts/quiz/generate-nba-500.mjs

import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"
import { deriveDifficulty } from "./difficulty.mjs"

const __dirname = dirname(fileURLToPath(import.meta.url))
const raw = readFileSync(join(__dirname, "nba-500.raw.txt"), "utf8")

const LETTER_TO_INDEX = { A: 0, B: 1, C: 2, D: 3, E: 4, F: 5 }

// Parse the flat text into { num, prompt, options[], answer } records.
const lines = raw.split("\n")
const questions = []
let cur = null

const startRe = /^(\d+)\.\s+(.*)$/
const optRe = /^([A-F])\)\s+(.*)$/
const ansRe = /^Answer:\s+([A-F])\b/

for (const line of lines) {
  const t = line.trim()
  if (!t) continue
  let m
  if ((m = t.match(ansRe))) {
    if (!cur) throw new Error(`Answer with no question: ${t}`)
    cur.answer = LETTER_TO_INDEX[m[1]]
    questions.push(cur)
    cur = null
  } else if ((m = t.match(optRe)) && cur) {
    cur.options.push(m[2])
  } else if ((m = t.match(startRe))) {
    if (cur) throw new Error(`Question ${cur.num} had no answer`)
    cur = { num: Number(m[1]), prompt: m[2], options: [], answer: -1 }
  }
}
if (cur) throw new Error(`Trailing question ${cur.num} had no answer`)

if (questions.length !== 500) {
  throw new Error(`Expected 500 questions, parsed ${questions.length}`)
}
for (const q of questions) {
  if (q.options.length < 2) throw new Error(`Q${q.num} has < 2 options`)
  if (q.answer < 0 || q.answer >= q.options.length) {
    throw new Error(`Q${q.num} has out-of-range answer ${q.answer}`)
  }
}

// Assign each question number to a category by theme, matching the ranges in
// the source material.
function categoryFor(num) {
  if (num >= 331 && num <= 392) return "nba-general" // rules & tactics
  if ((num >= 90 && num <= 171) || (num >= 453 && num <= 500)) return "nba-players" // awards, scorers, nicknames, Finals MVPs
  if (num >= 172 && num <= 255) return "nba-teams" // franchises, arenas, dynasties
  if (num >= 256 && num <= 330) return "nba-players" // draft lore -> players
  if (num >= 393 && num <= 452) return "nba-history" // duos, rivalries, playoff moments
  return "nba-history" // 1-89 memorable Finals plays
}

// Collapse the 4 themed categories down to just three buckets the UI shows:
// player, team, and mixed (everything else).
function bucketFor(num) {
  const cat = categoryFor(num)
  if (cat === "nba-players") return "player"
  if (cat === "nba-teams") return "team"
  return "mixed" // general + history
}

function esc(s) {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')
}

// Emit a flat, bucketed question list. data.ts assembles the three quizzes.
let out = ""
out += "// AUTO-GENERATED by scripts/quiz/generate-nba-500.mjs — do not edit by hand.\n"
out += "// Source: scripts/quiz/nba-500.raw.txt (500 NBA multiple-choice questions).\n"
out += "// Re-run the generator to regenerate.\n\n"
out += 'import type { BankQuestion } from "./types"\n\n'
out += "export const NBA_500_QUESTIONS: BankQuestion[] = [\n"

for (const q of questions) {
  out += "  {\n"
  out += `    id: "nba-500-q${q.num}",\n`
  out += `    bucket: "${bucketFor(q.num)}",\n`
  out += `    difficulty: "${deriveDifficulty(q.prompt)}",\n`
  out += `    prompt: "${esc(q.prompt)}",\n`
  out += `    options: [${q.options.map((o) => `"${esc(o)}"`).join(", ")}],\n`
  out += `    answer: ${q.answer},\n`
  out += "  },\n"
}
out += "]\n"

const target = join(__dirname, "..", "..", "lib", "quiz", "nba-500.ts")
writeFileSync(target, out)
console.log(`Wrote ${questions.length} questions to ${target}`)
