// ─── Curated Player Profiles ────────────────────────────────────────────────
//
// Hand-curated display quotes ("signature") and nicknames ("player_class") for
// NBA players, surfaced on the player ranking / profile pages.
//
// Design notes (see product spec):
//   • For established stars we use their recognizable real nicknames
//     (e.g. Stephen Curry → "Chef Curry", LeBron James → "King James").
//   • For rookies, fringe players, and obscure names we use a custom UI
//     nickname (e.g. "Rising Prospect", "The Ceiling is still rising") rather
//     than pretending it is an official nickname.
//
// Anything NOT present here falls back to the score-derived generic generator
// in `explanations.ts`, so the map only needs to cover known players.
//
// Matching is accent- and punctuation-insensitive so names like
// "Nikola Jokić", "Alperen Şengün", or "Luka Dončić" resolve correctly.

export interface PlayerProfile {
  /** Display quote — rendered as the italic signature line. */
  quote: string
  /** Display nickname — rendered as the "— NICKNAME" attribution. */
  nickname: string
}

/**
 * Normalize a player name for lookup: strip diacritics, lowercase, and reduce
 * to alphanumerics separated by single spaces. Keeps matching resilient to
 * accents, punctuation (periods, apostrophes), and casing differences.
 */
export function normalizePlayerName(name: string): string {
  return name
    .normalize("NFD")               // split accented chars into base + combining mark
    .replace(/[\u0300-\u036f]/g, "") // strip the combining marks
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")     // collapse punctuation/whitespace to single spaces
    .trim()
}

// Keyed by normalized player name → { quote, nickname }.
const RAW_PROFILES: Record<string, PlayerProfile> = {
  // ── A ──
  "A.J. Green": { quote: "Stay ready. Your moment always comes.", nickname: "The Veteran" },
  "A.J. Lawson": { quote: "Speed turns opportunity into impact.", nickname: "The Flyer" },
  "AJ Johnson": { quote: "The upside is only beginning.", nickname: "Rising Prospect" },
  "Aaron Gordon": { quote: "Explosiveness changes everything.", nickname: "AG" },
  "Aaron Holiday": { quote: "Small details. Big moments.", nickname: "Mr. Reliable" },
  "Aaron Nesmith": { quote: "Shoot without hesitation. Defend without compromise.", nickname: "The Sniper" },
  "Aaron Wiggins": { quote: "Quiet production speaks loudest.", nickname: "A-Wiggs" },
  "Ace Bailey": { quote: "Talent gets attention. Growth earns respect.", nickname: "The Ace" },
  "Adama-Alpha Bal": { quote: "The next chapter is waiting.", nickname: "Rising Guard" },
  "Adem Bona": { quote: "Bring force to every possession.", nickname: "The Enforcer" },
  "Adou Thiero": { quote: "Power becomes dangerous when refined.", nickname: "The Tank" },
  "Ajay Mitchell": { quote: "Control the game before it controls you.", nickname: "The Maestro" },
  "Al Horford": { quote: "Experience never goes out of style.", nickname: "Big Al" },
  "Alex Antetokounmpo": { quote: "Build your own name.", nickname: "The Antetokounmpo" },
  "Alex Caruso": { quote: "Effort is a skill too.", nickname: "Bald Eagle" },
  "Alex Morales": { quote: "Potential means nothing without patience.", nickname: "Rising Prospect" },
  "Alex Sarr": { quote: "Length creates possibilities.", nickname: "The Tower" },
  "Alijah Martin": { quote: "Keep climbing until they remember your name.", nickname: "Rising Wing" },
  "Alondes Williams": { quote: "Attack every opening.", nickname: "The Aggressor" },
  "Alperen Şengün": { quote: "Creativity has no position.", nickname: "Turkish Delight" },
  "Amari Williams": { quote: "Make every possession count.", nickname: "The Anchor" },
  "Amen Thompson": { quote: "Athleticism is only the beginning.", nickname: "The Blur" },
  "Amir Coffey": { quote: "Patience creates consistency.", nickname: "The Smooth Operator" },
  "Andersson Garcia": { quote: "The work speaks before the spotlight does.", nickname: "Rising Forward" },
  "Andre Drummond": { quote: "Own the glass. Own the paint.", nickname: "Big Penguin" },
  "Andre Jackson Jr.": { quote: "Defense travels everywhere.", nickname: "The Glue" },
  "Andrew Nembhard": { quote: "Steady hands win chaotic games.", nickname: "The General" },
  "Andrew Wiggins": { quote: "Silence the noise. Let the game answer.", nickname: "Maple Jordan" },
  "Anfernee Simons": { quote: "One shot can change the rhythm.", nickname: "Ant" },
  "Anthony Black": { quote: "See the game before it happens.", nickname: "AB" },
  "Anthony Davis": { quote: "Defense starts with presence.", nickname: "The Brow" },
  "Anthony Edwards": { quote: "Fear is fuel.", nickname: "Ant-Man" },
  "Anthony Gill": { quote: "Stay prepared. Stay useful.", nickname: "The Professional" },
  "Antonio Reeves": { quote: "Confidence grows one bucket at a time.", nickname: "The Scorer" },
  "Ariel Hukporti": { quote: "The foundation is already here.", nickname: "Rising Big" },
  "Asa Newell": { quote: "Potential becomes power through repetition.", nickname: "Rising Big" },
  "Ausar Thompson": { quote: "Impact doesn't always need a jumper.", nickname: "The Disruptor" },
  "Austin Reaves": { quote: "Make them remember the fourth quarter.", nickname: "AR15" },
  "Ayo Dosunmu": { quote: "Speed, strength, instinct.", nickname: "The Accelerator" },

  // ── B ──
  "Bam Adebayo": { quote: "Do everything. Guard everyone.", nickname: "Bam" },
  "Baylor Scheierman": { quote: "One clean look can change everything.", nickname: "The Marksman" },
  "Ben Saraf": { quote: "The ceiling is still moving.", nickname: "Rising Guard" },
  "Ben Sheppard": { quote: "Play smart. Play hard.", nickname: "The Grinder" },
  "Bennedict Mathurin": { quote: "Aggression creates opportunity.", nickname: "Benny" },
  "Bez Mbeng": { quote: "Every great run starts somewhere.", nickname: "Rising Prospect" },
  "Bilal Coulibaly": { quote: "Length. Speed. Untapped potential.", nickname: "Bilal" },
  "Bismack Biyombo": { quote: "Protect the paint. Protect the standard.", nickname: "The Mountain" },
  "Blake Hinson": { quote: "Let the jumper speak.", nickname: "The Gunner" },
  "Blake Wesley": { quote: "Attack the gaps.", nickname: "The Blur" },
  "Bobby Portis": { quote: "Energy changes the temperature.", nickname: "Bobby Buckets" },
  "Bobi Klintman": { quote: "Raw tools become weapons with time.", nickname: "Rising Forward" },
  "Bogdan Bogdanović": { quote: "Cold-blooded when the game heats up.", nickname: "Bogi" },
  "Bones Hyland": { quote: "Chaos has a rhythm.", nickname: "Bones" },
  "Bradley Beal": { quote: "When the game slows, attack.", nickname: "Big Panda" },
  "Branden Carlson": { quote: "Size creates an advantage. Skill makes it dangerous.", nickname: "The Tower" },
  "Brandin Podziemski": { quote: "Play bigger than the box score.", nickname: "Podz" },
  "Brandon Clarke": { quote: "Elevate above the defense.", nickname: "BC" },
  "Brandon Ingram": { quote: "Smooth never goes out of style.", nickname: "Slenderman" },
  "Brandon Miller": { quote: "Quiet confidence, loud results.", nickname: "B-Mill" },
  "Brandon Williams": { quote: "The opportunity belongs to whoever takes it.", nickname: "Rising Guard" },
  "Brice Sensabaugh": { quote: "Let the scoring come naturally.", nickname: "The Bucket" },
  "Bronny James": { quote: "The name opens the door. The work keeps it open.", nickname: "Bronny" },
  "Brook Lopez": { quote: "Protect the rim. Stretch the floor.", nickname: "Splash Mountain" },
  "Brooks Barnhizer": { quote: "Motor matters.", nickname: "Rising Wing" },
  "Bruce Brown": { quote: "Do the little things that win.", nickname: "Playoff B" },
  "Bryce McGowens": { quote: "Patience turns potential into production.", nickname: "Rising Scorer" },
  "Bub Carrington": { quote: "Young legs. Veteran instincts.", nickname: "Bub" },

  // ── C ──
  "Buddy Boeheim": { quote: "Let it fly.", nickname: "The Shooter" },
  "Buddy Hield": { quote: "Never hesitate from deep.", nickname: "Buddy Buckets" },
  "CJ Huntley": { quote: "The next opportunity starts today.", nickname: "Rising Prospect" },
  "CJ McCollum": { quote: "Craft beats chaos.", nickname: "Three-J" },
  "Cade Cunningham": { quote: "Control the game. Control the pace.", nickname: "Cade" },
  "Caleb Houstan": { quote: "Make the open shot count.", nickname: "The Sniper" },
  "Caleb Love": { quote: "Confidence travels.", nickname: "CL" },
  "Caleb Martin": { quote: "Built for the big stage.", nickname: "Caleb" },
  "Cam Christie": { quote: "The jumper is only the beginning.", nickname: "Rising Shooter" },
  "Cam Spencer": { quote: "Find the shot. Take the shot.", nickname: "Cam" },
  "Cam Thomas": { quote: "Buckets don't need permission.", nickname: "Mr. Bucket" },
  "Cam Whitmore": { quote: "Power through the hesitation.", nickname: "Cam" },
  "Cameron Johnson": { quote: "A clean release changes everything.", nickname: "Cam Johnson" },
  "Cameron Payne": { quote: "Speed the game up.", nickname: "Campaign" },
  "Caris LeVert": { quote: "Versatility keeps doors open.", nickname: "Caris" },
  "Carter Bryant": { quote: "Two-way potential is dangerous.", nickname: "Rising Wing" },
  "Cason Wallace": { quote: "Pressure creates mistakes. Be the pressure.", nickname: "C-Wall" },
  "Cedric Coward": { quote: "Potential becomes real when the game slows down.", nickname: "The Sleeper" },
  "Chaney Johnson": { quote: "Keep stacking the pieces.", nickname: "Rising Forward" },
  "Charles Bassey": { quote: "Protect the paint with purpose.", nickname: "The Anchor" },
  "Chaz Lanier": { quote: "Shooters change games quickly.", nickname: "The Gunner" },
  "Chet Holmgren": { quote: "Skill makes size unfair.", nickname: "Chet" },
  "Chris Boucher": { quote: "Bring length to every possession.", nickname: "Slim Reaper" },
  "Chris Livingston": { quote: "Patience is part of the process.", nickname: "Rising Wing" },
  "Chris Mañon": { quote: "The next opportunity is yours.", nickname: "Rising Prospect" },
  "Chris Paul": { quote: "Command the game.", nickname: "CP3" },
  "Chris Youngblood": { quote: "Keep building the next level.", nickname: "Rising Prospect" },
  "Christian Braun": { quote: "Defense travels. Confidence follows.", nickname: "CB" },
  "Christian Koloko": { quote: "Protect the rim.", nickname: "The Rim Protector" },
  "Chucky Hepburn": { quote: "The floor is yours.", nickname: "Rising Guard" },
  "Clint Capela": { quote: "Own the paint.", nickname: "The Lob Monster" },
  "Coby White": { quote: "Let the speed take over.", nickname: "White Lightning" },
  "Cody Martin": { quote: "Versatility is value.", nickname: "Cody" },
  "Cody Williams": { quote: "The ceiling is still rising.", nickname: "Rising Wing" },
  "Colby Jones": { quote: "Keep the game simple.", nickname: "The Connector" },
  "Cole Anthony": { quote: "Play with your heart on every possession.", nickname: "Cole World" },
  "Colin Castleton": { quote: "Big bodies make big problems.", nickname: "Rising Big" },
  "Collin Gillespie": { quote: "IQ can beat athleticism.", nickname: "The Floor General" },
  "Collin Murray-Boyles": { quote: "Strength travels.", nickname: "Rising Forward" },
  "Collin Sexton": { quote: "Bring the speed every night.", nickname: "Young Bull" },
  "Cooper Flagg": { quote: "Defense starts the story. Everything else follows.", nickname: "The Flag" },

  // ── D ──
  "Corey Kispert": { quote: "One inch of daylight is enough.", nickname: "The Sharpshooter" },
  "Cormac Ryan": { quote: "Stay ready for the moment.", nickname: "The Shooter" },
  "Craig Porter Jr.": { quote: "Control the tempo.", nickname: "The Conductor" },
  "Curtis Jones": { quote: "Every possession is another opportunity.", nickname: "Rising Guard" },
  "D'Angelo Russell": { quote: "Confidence makes impossible passes look easy.", nickname: "DLo" },
  "DaQuan Jeffries": { quote: "Stay ready. Stay dangerous.", nickname: "The Wing" },
  "DaRon Holmes": { quote: "The paint belongs to the fearless.", nickname: "Rising Big" },
  "Daeqwon Plowden": { quote: "Keep attacking the opportunity.", nickname: "Rising Wing" },
  "Dalano Banton": { quote: "Size changes the angles.", nickname: "The Long Guard" },
  "Dalen Terry": { quote: "Energy never goes out of style.", nickname: "DT" },
  "Dalton Knecht": { quote: "Catch. Rise. Fire.", nickname: "The Marksman" },
  "Daniel Gafford": { quote: "Meet the rim above the rim.", nickname: "DG" },
  "Daniss Jenkins": { quote: "The next play is always yours.", nickname: "Rising Guard" },
  "Danny Wolf": { quote: "Smart players see space differently.", nickname: "The Big Facilitator" },
  "Dario Šarić": { quote: "Skill travels across generations.", nickname: "The Homie" },
  "Dariq Whitehead": { quote: "The talent is still there.", nickname: "Rising Wing" },
  "Darius Brown II": { quote: "Build momentum, one possession at a time.", nickname: "Rising Guard" },
  "Darius Garland": { quote: "Small space. Big creation.", nickname: "DG" },
  "David Jones García": { quote: "Aggression can open every door.", nickname: "Rising Wing" },
  "David Roddy": { quote: "Strength creates its own lane.", nickname: "Showtime" },
  "Davion Mitchell": { quote: "Pressure starts at half court.", nickname: "Off Night" },
  "Day'Ron Sharpe": { quote: "Own the rebound. Own the possession.", nickname: "The Beast" },
  "De'Aaron Fox": { quote: "Speed becomes unstoppable when controlled.", nickname: "Swipa" },
  "De'Andre Hunter": { quote: "Patience turns defense into offense.", nickname: "The Hunter" },
  "De'Anthony Melton": { quote: "Disruption creates opportunity.", nickname: "Mr. Do Something" },
  "DeAndre Jordan": { quote: "Protect the rim. Lead the room.", nickname: "DJ" },
  "DeJon Jarreau": { quote: "Make every possession uncomfortable.", nickname: "The Pest" },
  "DeMar DeRozan": { quote: "Midrange is an art.", nickname: "Deebo" },
  "Dean Wade": { quote: "Do your job every night.", nickname: "The Utility" },
  "Deandre Ayton": { quote: "Power starts with presence.", nickname: "DominAyton" },
  "Dejounte Murray": { quote: "See everything. Control everything.", nickname: "Baby Joker" },
  "Deni Avdija": { quote: "Versatility makes the game easier.", nickname: "Deni" },
  "Dennis Schröder": { quote: "Push the pace.", nickname: "Dennis the Menace" },
  "Dereck Lively II": { quote: "Verticality changes the paint.", nickname: "DLive" },
  "Derik Queen": { quote: "Inside skill creates outside problems.", nickname: "The Queen" },
  "Derrick Jones Jr.": { quote: "The sky is never too high.", nickname: "Airplane Mode" },
  "Derrick White": { quote: "Do everything right.", nickname: "The Buffalo" },
  "Desmond Bane": { quote: "Strength turns separation into certainty.", nickname: "Bane" },
  "Devin Booker": { quote: "Pure scoring is an art.", nickname: "Book" },
  "Devin Carter": { quote: "Defense travels with you.", nickname: "Rising Guard" },
  "Devin Vassell": { quote: "Smooth scoring under pressure.", nickname: "Vassell" },
  "Dillon Brooks": { quote: "Make every matchup personal.", nickname: "The Villain" },
  "Dillon Jones": { quote: "Attack with purpose.", nickname: "Rising Wing" },
  "Domantas Sabonis": { quote: "The offense begins with the big man.", nickname: "Domas" },
  "Dominick Barlow": { quote: "Keep growing into your game.", nickname: "Rising Forward" },
  "Donovan Clingan": { quote: "The paint has a new owner.", nickname: "The Big Fella" },
  "Donovan Mitchell": { quote: "Light the arena.", nickname: "Spida" },
  "Donte DiVincenzo": { quote: "Do the dirty work and hit the big shot.", nickname: "The Big Ragu" },
  "Dorian Finney-Smith": { quote: "Versatility survives every matchup.", nickname: "DFS" },
  "Doug McDermott": { quote: "Never waste an open look.", nickname: "Dougie McBuckets" },
  "Drake Powell": { quote: "The future moves fast.", nickname: "Rising Wing" },
  "Draymond Green": { quote: "Impact isn't always measured in points.", nickname: "Day-Day" },
  "Drew Eubanks": { quote: "Bring the force inside.", nickname: "D-Block" },
  "Drew Peterson": { quote: "Make the smart play.", nickname: "The Connector" },
  "Drew Timme": { quote: "Toughness travels.", nickname: "The Big Fundamental" },
  "Dru Smith": { quote: "Stay ready for every assignment.", nickname: "The Specialist" },
  "Duncan Robinson": { quote: "One shot can bend a defense.", nickname: "Duncan" },
  "Duop Reath": { quote: "Size plus touch changes the equation.", nickname: "The Stretch Big" },
  "Dwight Powell": { quote: "Consistency is a skill.", nickname: "DP" },
  "Dylan Cardwell": { quote: "Own the glass.", nickname: "Rising Big" },
  "Dylan Harper": { quote: "Vision, size, control.", nickname: "The Young General" },
  "Dyson Daniels": { quote: "Make every possession difficult.", nickname: "The Great Barrier" },

  // ── E–H ──
  "E.J. Liddell": { quote: "Strength gives the game a foundation.", nickname: "Rising Forward" },
  "Egor Dëmin": { quote: "The ceiling is still out of sight.", nickname: "The Russian Prospect" },
  "Elijah Harkless": { quote: "Defense creates your next opportunity.", nickname: "The Stopper" },
  "Emanuel Miller": { quote: "Toughness travels.", nickname: "Rising Forward" },
  "Enrique Freeman": { quote: "Rebounding is a mentality.", nickname: "The Hustler" },
  "Eric Gordon": { quote: "Shooters never stop being dangerous.", nickname: "EJ" },
  "Ethan Thompson": { quote: "Keep earning the next possession.", nickname: "Rising Guard" },
  "Evan Mobley": { quote: "Length, intelligence, control.", nickname: "Mobley" },
  "Franz Wagner": { quote: "Smooth decisions create hard problems.", nickname: "The Prince" },
  "GG Jackson II": { quote: "Potential gets loud when confidence arrives.", nickname: "GG" },
  "Gabe Vincent": { quote: "Big moments need calm players.", nickname: "Gabe" },
  "Garrett Temple": { quote: "Experience makes the game slower.", nickname: "The Elder" },
  "Garrison Mathews": { quote: "One open look is all you need.", nickname: "Garrison" },
  "Gary Harris": { quote: "Stay ready on both ends.", nickname: "G-Money" },
  "Gary Payton II": { quote: "Defense is an attitude.", nickname: "Young Glove" },
  "Gary Trent Jr.": { quote: "Let the jumper decide.", nickname: "GTJ" },
  "Giannis Antetokounmpo": { quote: "Keep improving until impossible looks ordinary.", nickname: "The Greek Freak" },
  "Goga Bitadze": { quote: "Protect the paint with patience.", nickname: "Goga" },
  "Gradey Dick": { quote: "The jumper travels anywhere.", nickname: "Gradey" },
  "Grant Nelson": { quote: "Keep turning potential into production.", nickname: "Rising Forward" },
  "Grant Williams": { quote: "Make every matchup uncomfortable.", nickname: "Batman" },
  "Grayson Allen": { quote: "Don't hesitate. Don't apologize.", nickname: "The Accountant" },
  "Guerschon Yabusele": { quote: "Power belongs in the modern game.", nickname: "The Dancing Bear" },
  "Gui Santos": { quote: "The upside is only beginning.", nickname: "Rising Wing" },
  "Harrison Barnes": { quote: "Consistency is its own superpower.", nickname: "HB" },
  "Harrison Ingram": { quote: "Effort gives talent a foundation.", nickname: "Rising Wing" },
  "Hayden Gray": { quote: "Every level starts with belief.", nickname: "Rising Prospect" },
  "Haywood Highsmith": { quote: "Defense creates a career.", nickname: "H" },
  "Herbert Jones": { quote: "Make the game uncomfortable.", nickname: "The Stinger" },
  "Hugo González": { quote: "The tools are already there.", nickname: "Rising Star" },
  "Hunter Dickinson": { quote: "Own the interior.", nickname: "The Big Cat" },
  "Hunter Sallis": { quote: "Let your confidence catch up to your talent.", nickname: "Rising Guard" },
  "Hunter Tyson": { quote: "Shooters punish hesitation.", nickname: "The Sniper" },

  // ── I–L ──
  "Immanuel Quickley": { quote: "Pace is a weapon.", nickname: "IQ" },
  "Isaac Jones": { quote: "Keep attacking the rim.", nickname: "Rising Big" },
  "Isaac Okoro": { quote: "Defense is the foundation.", nickname: "The Lock" },
  "Isaiah Collier": { quote: "Fast decisions create fast offense.", nickname: "Rising Guard" },
  "Isaiah Crawford": { quote: "Make your versatility matter.", nickname: "Rising Wing" },
  "Isaiah Hartenstein": { quote: "Rebounding is positioning and desire.", nickname: "The Big Screen" },
  "Isaiah Jackson": { quote: "Protect the rim, attack the glass.", nickname: "IJ" },
  "Isaiah Joe": { quote: "One shot changes everything.", nickname: "Joe Cool" },
  "Isaiah Livers": { quote: "Keep finding your rhythm.", nickname: "Rising Wing" },
  "Isaiah Stevens": { quote: "IQ makes speed irrelevant.", nickname: "The Floor General" },
  "Isaiah Stewart": { quote: "Bring the fight inside.", nickname: "Beef Stew" },
  "Ivica Zubac": { quote: "The paint belongs to the relentless.", nickname: "Zu" },
  "JD Davison": { quote: "Pressure creates opportunity.", nickname: "Rising Guard" },
  "Ja Morant": { quote: "Gravity can't stop the leap.", nickname: "G12" },
  "Ja'Kobe Walter": { quote: "Shooters grow into stars.", nickname: "Rising Scorer" },
  "Jabari Smith Jr.": { quote: "Height plus skill changes the geometry.", nickname: "Jabari" },
  "Jabari Walker": { quote: "Let the work build the confidence.", nickname: "Rising Forward" },
  "Jacob Toppin": { quote: "Attack the sky.", nickname: "Rising Flyer" },
  "Jaden Hardy": { quote: "Confidence turns creation into scoring.", nickname: "J-Hardy" },
  "Jaden Ivey": { quote: "Speed breaks defenses.", nickname: "JI" },
  "Jaden McDaniels": { quote: "Length makes every possession harder.", nickname: "J-Mac" },
  "Jae'Sean Tate": { quote: "Do the work nobody notices.", nickname: "The Tough One" },
  "Jahmai Mashack": { quote: "Defense opens doors.", nickname: "Rising Guard" },
  "Jahmir Young": { quote: "Control the pace.", nickname: "The Commander" },
  "Jahmyl Telfort": { quote: "Keep climbing.", nickname: "Rising Wing" },
  "Jaime Jaquez Jr.": { quote: "Old-school toughness in a new era.", nickname: "Triple J" },
  "Jake LaRavia": { quote: "Play every role with purpose.", nickname: "The Utility" },
  "Jakob Poeltl": { quote: "Own the paint without forcing it.", nickname: "The Big Austrian" },
  "Jalen Brunson": { quote: "Heart beats size.", nickname: "Young Star" },
  "Jalen Duren": { quote: "Power your way through the paint.", nickname: "JD" },
  "Jalen Green": { quote: "The rim is never too far.", nickname: "JG4" },
  "Jalen Johnson": { quote: "Versatility makes the game simple.", nickname: "JJ" },
  "Jalen Pickett": { quote: "Craft beats chaos.", nickname: "The Technician" },
  "Jalen Slawson": { quote: "Keep building the complete game.", nickname: "Rising Forward" },
  "Jalen Smith": { quote: "Bring size with skill.", nickname: "Stix" },
  "Jalen Suggs": { quote: "Pressure every possession.", nickname: "Suggs" },
  "Jalen Williams": { quote: "Efficiency makes greatness look easy.", nickname: "JDub" },
  "Jalen Wilson": { quote: "Keep earning every minute.", nickname: "Rising Wing" },
  "Jamal Cain": { quote: "Energy creates opportunity.", nickname: "Rising Wing" },
  "Jamal Murray": { quote: "Save your best for the brightest lights.", nickname: "Blue Arrow" },
  "Jamal Shead": { quote: "Defense starts with attitude.", nickname: "Rising Guard" },
  "Jamaree Bouyea": { quote: "Keep making the next play.", nickname: "Rising Guard" },
  "James Harden": { quote: "Slow the game down. Own it.", nickname: "The Beard" },
  "James Wiseman": { quote: "The tools are too big to ignore.", nickname: "Big Wise" },
  "Jamir Watkins": { quote: "Explosiveness creates separation.", nickname: "Rising Wing" },
  "Jamison Battle": { quote: "Let your shot travel.", nickname: "JB" },
  "Jarace Walker": { quote: "Strength creates versatility.", nickname: "Rising Forward" },
  "Jared McCain": { quote: "Confidence is contagious.", nickname: "McNasty" },
  "Jaren Jackson Jr.": { quote: "Protect the rim. Stretch the floor.", nickname: "Triple J" },
  "Jarred Vanderbilt": { quote: "Defense is effort made visible.", nickname: "Vando" },
  "Jarrett Allen": { quote: "Protect everything above the rim.", nickname: "Fro" },
  "Jase Richardson": { quote: "The next generation arrives fast.", nickname: "Rising Guard" },
  "Javon Small": { quote: "Every possession is another chance.", nickname: "Rising Guard" },
  "Javonte Cooke": { quote: "Keep chasing the next level.", nickname: "Rising Prospect" },
  "Javonte Green": { quote: "Athleticism creates second chances.", nickname: "JG" },
  "Jaxson Hayes": { quote: "Meet the rim at the top.", nickname: "Jaxson" },
  "Jay Huff": { quote: "Seven feet changes the equation.", nickname: "Rising Big" },
  "Jaylen Brown": { quote: "Strength. Purpose. Progress.", nickname: "JB" },
  "Jaylen Clark": { quote: "Defense is identity.", nickname: "The Lock" },
  "Jaylen Wells": { quote: "Let the game come to you.", nickname: "Rising Wing" },
  "Jaylin Williams": { quote: "Make the smart play.", nickname: "J-Will" },
  "Jaylon Tyson": { quote: "Every role can become a weapon.", nickname: "Rising Wing" },
  "Jayson Kent": { quote: "Keep building the foundation.", nickname: "Rising Forward" },
  "Jayson Tatum": { quote: "Don't chase greatness. Become it.", nickname: "JT" },
  "Jeff Green": { quote: "Experience gives you another gear.", nickname: "Uncle Jeff" },
  "Jerami Grant": { quote: "Length becomes lethal with confidence.", nickname: "Jerami" },
  "Jeremiah Fears": { quote: "Fear is just another word for opportunity.", nickname: "Rising Guard" },
  "Jeremiah Robinson-Earl": { quote: "Do the little things that matter.", nickname: "JRE" },
  "Jeremy Sochan": { quote: "Chaos can be creativity.", nickname: "Young Wolf" },
  "Jericho Sims": { quote: "The rim is a meeting point.", nickname: "Rising Big" },
  "Jett Howard": { quote: "One clean release changes everything.", nickname: "Jett" },
  "Jevon Carter": { quote: "Defend first. Everything follows.", nickname: "Mr. 94 Feet" },
  "Jimmy Butler": { quote: "Work wins when talent gets tired.", nickname: "Jimmy Buckets" },
  "Joan Beringer": { quote: "The tools are rare. The journey is just starting.", nickname: "Rising Big" },
  "Jock Landale": { quote: "Bring toughness to the interior.", nickname: "Jock" },
  "Joe Ingles": { quote: "Let experience control the game.", nickname: "Slow Mo" },
  "Joel Embiid": { quote: "Trust the process. Own the moment.", nickname: "The Process" },
  "John Collins": { quote: "Finish above the defense.", nickname: "JC" },
  "John Konchar": { quote: "Every team needs a connector.", nickname: "Jitty" },
  "John Poulakidas": { quote: "A shooter only needs one opening.", nickname: "Rising Shooter" },
  "John Tonje": { quote: "Confidence turns opportunity into points.", nickname: "Rising Scorer" },
  "Johni Broome": { quote: "Control the paint. Control the game.", nickname: "Rising Big" },
  "Johnny Furphy": { quote: "The next level rewards patience.", nickname: "Rising Wing" },
  "Johnny Juzang": { quote: "Buckets come from belief.", nickname: "Juzang" },
  "Jonas Valančiūnas": { quote: "Old-school power still works.", nickname: "JV" },
  "Jonathan Isaac": { quote: "Length creates defensive gravity.", nickname: "JI" },
  "Jonathan Kuminga": { quote: "Raw power becomes unstoppable with polish.", nickname: "JK" },
  "Jonathan Mogbo": { quote: "Athleticism creates possibilities.", nickname: "Rising Forward" },
  "Jordan Clarkson": { quote: "Heat checks are part of the job.", nickname: "JC" },
  "Jordan Goodwin": { quote: "Defend. Rebound. Compete.", nickname: "Goodwin" },
  "Jordan Hawkins": { quote: "Never stop running.", nickname: "Hawk" },
  "Jordan McLaughlin": { quote: "Control the second unit.", nickname: "J-Mac" },
  "Jordan Miller": { quote: "Keep climbing through the noise.", nickname: "Rising Wing" },
  "Jordan Poole": { quote: "Chaos creates highlights.", nickname: "JP" },
  "Jordan Walsh": { quote: "Defense gives you a role.", nickname: "Rising Wing" },
  "Jose Alvarado": { quote: "Pressure is a personality.", nickname: "Grand Theft Alvarado" },
  "Josh Giddey": { quote: "See the pass before the defense.", nickname: "Giddey" },
  "Josh Green": { quote: "Play fast, think faster.", nickname: "JG" },
  "Josh Hart": { quote: "Winning plays don't need a spotlight.", nickname: "Josh Hart" },
  "Josh Minott": { quote: "Athleticism is a foundation.", nickname: "Rising Wing" },
  "Josh Oduro": { quote: "Strength earns space.", nickname: "Rising Big" },
  "Josh Okogie": { quote: "Make every scorer uncomfortable.", nickname: "The Pest" },
  "Jrue Holiday": { quote: "Defense is possession control.", nickname: "Uncle Drew" },
  "Julian Champagnie": { quote: "Stay ready for the corner.", nickname: "Rising Shooter" },
  "Julian Phillips": { quote: "Let athleticism become consistency.", nickname: "Rising Wing" },
  "Julian Reese": { quote: "Own your space.", nickname: "Rising Big" },
  "Julian Strawther": { quote: "Let it fly.", nickname: "The Shooter" },
  "Julius Randle": { quote: "Force your way to the finish.", nickname: "Beyblade" },
  "Justin Champagnie": { quote: "Keep the pressure on.", nickname: "Rising Wing" },
  "Justin Edwards": { quote: "The ceiling is high. Keep climbing.", nickname: "Rising Wing" },
  "Jusuf Nurkić": { quote: "Make the paint a problem.", nickname: "The Bosnian Beast" },

  // ── K–M ──
  "KJ Simpson": { quote: "Keep the engine running.", nickname: "Rising Guard" },
  "Kadary Richmond": { quote: "Every possession has purpose.", nickname: "Rising Guard" },
  "Kam Jones": { quote: "Confidence travels with the jumper.", nickname: "Rising Guard" },
  "Karl-Anthony Towns": { quote: "Size, touch, range.", nickname: "KAT" },
  "Karlo Matković": { quote: "Length creates another dimension.", nickname: "Rising Big" },
  "Kasparas Jakučionis": { quote: "The vision is already there.", nickname: "Rising Playmaker" },
  "Kawhi Leonard": { quote: "Quiet is deadly.", nickname: "The Klaw" },
  "Keaton Wallace": { quote: "Stay ready. Stay steady.", nickname: "Rising Guard" },
  "Keegan Murray": { quote: "The jumper changes everything.", nickname: "Keegan" },
  "Kel'el Ware": { quote: "The upside starts with the tools.", nickname: "Rising Big" },
  "Keldon Johnson": { quote: "Attack every opening.", nickname: "Big Body" },
  "Kelly Olynyk": { quote: "Big men can create too.", nickname: "KO" },
  "Kelly Oubre Jr.": { quote: "Confidence looks good in motion.", nickname: "Tsunami Papi" },
  "Kennedy Chandler": { quote: "Control the pace.", nickname: "Rising Guard" },
  "Kenrich Williams": { quote: "Do whatever winning requires.", nickname: "Kenrich" },
  "Kentavious Caldwell-Pope": { quote: "Defend. Move. Shoot.", nickname: "KCP" },
  "Keon Ellis": { quote: "Defense creates your value.", nickname: "Rising Guard" },
  "Keshad Johnson": { quote: "Toughness opens doors.", nickname: "Rising Wing" },
  "Keshon Gilbert": { quote: "Keep attacking the next level.", nickname: "Rising Guard" },
  "Kevin Durant": { quote: "Greatness looks effortless when preparation is endless.", nickname: "Slim Reaper" },
  "Kevin Huerter": { quote: "One clean look is enough.", nickname: "Red Velvet" },
  "Kevin Love": { quote: "Let the experience stretch the floor.", nickname: "K-Love" },
  "Kevin McCullar Jr.": { quote: "Impact doesn't require volume.", nickname: "Rising Wing" },
  "Kevin Porter Jr.": { quote: "Creation starts with confidence.", nickname: "KPJ" },
  "Kevon Looney": { quote: "The little things win championships.", nickname: "Loon" },
  "Keyonte George": { quote: "Let the scorer emerge.", nickname: "Rising Guard" },
  "Khaman Maluach": { quote: "The ceiling begins at seven feet.", nickname: "The Tower" },
  "Khris Middleton": { quote: "Calm is a weapon.", nickname: "Khri$" },
  "Killian Hayes": { quote: "Control the tempo.", nickname: "Rising Guard" },
  "Klay Thompson": { quote: "Sometimes one quarter is all it takes.", nickname: "Game 6 Klay" },
  "Kobe Brown": { quote: "Play bigger than the moment.", nickname: "Rising Forward" },
  "Kobe Bufkin": { quote: "The next jump is waiting.", nickname: "Rising Guard" },
  "Kobe Sanders": { quote: "Let the next level find you ready.", nickname: "Rising Wing" },
  "Koby Brea": { quote: "Never waste an open shot.", nickname: "The Marksman" },
  "Kon Knueppel": { quote: "Skill travels faster than hype.", nickname: "Rising Shooter" },
  "Kris Dunn": { quote: "Defense travels.", nickname: "The Bulldog" },
  "Kris Murray": { quote: "Consistency becomes confidence.", nickname: "Rising Wing" },
  "Kristaps Porziņģis": { quote: "Seven feet of skill changes everything.", nickname: "The Unicorn" },
  "Kyle Anderson": { quote: "Slow the game down.", nickname: "Slo Mo" },
  "Kyle Filipowski": { quote: "Skill makes size dangerous.", nickname: "Flip" },
  "Kyle Kuzma": { quote: "Make noise with your own style.", nickname: "Kuz" },
  "Kyle Lowry": { quote: "Sacrifice makes winning possible.", nickname: "K-Low" },
  "Kyshawn George": { quote: "The game rewards size and patience.", nickname: "Rising Wing" },
  "LJ Cryer": { quote: "Every clean look counts.", nickname: "The Shooter" },
  "LaMelo Ball": { quote: "Make the impossible entertaining.", nickname: "Melo" },
  "Lachlan Olbrich": { quote: "The next level starts with confidence.", nickname: "Rising Prospect" },
  "Landry Shamet": { quote: "Never hesitate.", nickname: "The Shooter" },
  "Larry Nance Jr.": { quote: "Athleticism runs in the family.", nickname: "Jr." },
  "Lauri Markkanen": { quote: "Seven feet of pure shooting.", nickname: "The Finnisher" },
  "Lawson Lovering": { quote: "Let the foundation get stronger.", nickname: "Rising Big" },
  "LeBron James": { quote: "Greatness is built for the moments that matter.", nickname: "King James" },
  "League Average": { quote: "The standard everyone is measured against.", nickname: "The Baseline" },
  "Leaky Black": { quote: "Defense gives you a place.", nickname: "Rising Wing" },
  "Leonard Miller": { quote: "The tools are too intriguing to ignore.", nickname: "Rising Forward" },
  "Liam McNeeley": { quote: "Let the jumper introduce you.", nickname: "Rising Wing" },
  "Lindy Waters III": { quote: "One shot can change a game.", nickname: "The Sniper" },
  "Lonzo Ball": { quote: "See the court differently.", nickname: "Zo" },
  "Lucas Williamson": { quote: "Smart basketball lasts.", nickname: "Rising Guard" },
  "Luguentz Dort": { quote: "Every possession is a fight.", nickname: "Dorture Chamber" },
  "Luka Dončić": { quote: "Slow pace. Impossible results.", nickname: "Luka Magic" },
  "Luka Garza": { quote: "Buckets come in every form.", nickname: "The Big Bucket" },
  "Luke Kennard": { quote: "Leave no open shot unused.", nickname: "The Sharpshooter" },
  "Luke Kornet": { quote: "Seven feet of hustle.", nickname: "Luke" },

  // ── M–P ──
  "Mac McClung": { quote: "The spotlight belongs to whoever attacks it.", nickname: "Mac" },
  "Malachi Smith": { quote: "Keep the next play simple.", nickname: "Rising Guard" },
  "Malaki Branham": { quote: "Let patience become production.", nickname: "Rising Scorer" },
  "Malevy Leons": { quote: "The opportunity is still unfolding.", nickname: "Rising Forward" },
  "Malik Monk": { quote: "Turn energy into points.", nickname: "Monk" },
  "MarJon Beauchamp": { quote: "Athleticism becomes dangerous with confidence.", nickname: "Rising Wing" },
  "Marcus Sasser": { quote: "Small guard, big confidence.", nickname: "Mighty Mouse" },
  "Marcus Smart": { quote: "Heart makes up for everything.", nickname: "Cobra" },
  "Mark Sears": { quote: "Shooters don't blink.", nickname: "Rising Scorer" },
  "Mark Williams": { quote: "Own the paint.", nickname: "The Big" },
  "Markelle Fultz": { quote: "The comeback is part of the story.", nickname: "Kelle" },
  "Marvin Bagley III": { quote: "Verticality creates opportunity.", nickname: "Bagley" },
  "Mason Plumlee": { quote: "Do the winning work.", nickname: "Plumdog" },
  "Matas Buzelis": { quote: "The ceiling starts with imagination.", nickname: "Rising Wing" },
  "Matisse Thybulle": { quote: "Steals are momentum.", nickname: "Tisse" },
  "Max Christie": { quote: "The next leap starts with consistency.", nickname: "Rising Wing" },
  "Max Shulga": { quote: "The game is still getting bigger.", nickname: "Rising Guard" },
  "Max Strus": { quote: "No hesitation.", nickname: "The Strus" },
  "Maxi Kleber": { quote: "Positionless skill has value.", nickname: "Maxi" },
  "Maxime Raynaud": { quote: "Size, touch, production.", nickname: "Rising Big" },
  "Micah Peavy": { quote: "Keep climbing.", nickname: "Rising Wing" },
  "Micah Potter": { quote: "The shot always has a place.", nickname: "The Stretch Big" },
  "Michael Porter Jr.": { quote: "Rise above the contest.", nickname: "MPJ" },
  "Mikal Bridges": { quote: "Reliability is a superpower.", nickname: "The Ironman" },
  "Mike Conley": { quote: "Lead without needing the spotlight.", nickname: "Uncle Mike" },
  "Miles Bridges": { quote: "Bring the force every night.", nickname: "Mile High" },
  "Miles Kelly": { quote: "Let the next opportunity become yours.", nickname: "Rising Wing" },
  "Miles McBride": { quote: "Pressure never stops.", nickname: "Deuce" },
  "Mitchell Robinson": { quote: "Protect the rim at all costs.", nickname: "Blockinson" },
  "Mo Bamba": { quote: "Length changes the game.", nickname: "Mo" },
  "Mohamed Diawara": { quote: "Raw tools can become special.", nickname: "Rising Forward" },
  "Monte Morris": { quote: "Steady hands win games.", nickname: "Money" },
  "Moritz Wagner": { quote: "Bring energy, then bring chaos.", nickname: "Moe" },
  "Moses Moody": { quote: "Stay patient. Keep improving.", nickname: "Moody" },
  "Mouhamadou Gueye": { quote: "The upside starts with effort.", nickname: "Rising Forward" },
  "Mouhamed Gueye": { quote: "Let the tools develop.", nickname: "Rising Big" },
  "Moussa Cisse": { quote: "Protect the paint with force.", nickname: "The Anchor" },
  "Moussa Diabaté": { quote: "Athleticism opens the door.", nickname: "Rising Big" },
  "Myles Turner": { quote: "Blocks and buckets.", nickname: "Myles" },
  "Myron Gardner": { quote: "The next step belongs to the hungry.", nickname: "Rising Forward" },
  "N'Faly Dante": { quote: "Own every inch of the paint.", nickname: "The Enforcer" },
  "Nae'Qwan Tomlin": { quote: "Keep making the next play.", nickname: "Rising Forward" },
  "Naji Marshall": { quote: "Make every matchup count.", nickname: "Naji" },
  "Nate Williams": { quote: "Opportunity rewards readiness.", nickname: "Rising Guard" },
  "Naz Reid": { quote: "Let the big man shoot.", nickname: "NAZ Reid" },
  "Neemias Queta": { quote: "Protect the glass.", nickname: "Rising Big" },
  "Nic Claxton": { quote: "Defense changes the entire floor.", nickname: "Clax" },
  "Nick Richards": { quote: "Own the interior.", nickname: "Rising Big" },
  "Nick Smith Jr.": { quote: "The jumper can change everything.", nickname: "Rising Guard" },
  "Nickeil Alexander-Walker": { quote: "Versatility is the weapon.", nickname: "NAW" },
  "Nicolas Batum": { quote: "Experience fills every gap.", nickname: "Batman" },
  "Nigel Hayes-Davis": { quote: "Keep expanding the game.", nickname: "Rising Forward" },
  "Nikola Jokić": { quote: "Make the difficult look effortless.", nickname: "The Joker" },
  "Nikola Jović": { quote: "Size creates a different kind of skill.", nickname: "Rising Forward" },
  "Nikola Topić": { quote: "See the next pass first.", nickname: "Rising Guard" },
  "Nikola Vučević": { quote: "Skill from the middle changes everything.", nickname: "Vooch" },
  "Nique Clifford": { quote: "Production always finds its level.", nickname: "Rising Wing" },
  "Noa Essengue": { quote: "The raw tools are already rare.", nickname: "Rising Forward" },
  "Noah Clowney": { quote: "Let the length do the damage.", nickname: "Rising Big" },
  "Noah Penda": { quote: "Potential becomes production with time.", nickname: "Rising Forward" },
  "Nolan Traoré": { quote: "Speed creates the first advantage.", nickname: "Rising Guard" },
  "Norchad Omier": { quote: "Toughness starts inside.", nickname: "Rising Big" },
  "Norman Powell": { quote: "Instant offense is a skill.", nickname: "Playoff Powell" },
  "OG Anunoby": { quote: "Make stars work for every point.", nickname: "OG" },
  "Obi Toppin": { quote: "Elevate the ordinary.", nickname: "Obi" },
  "Ochai Agbaji": { quote: "Make the open shot count.", nickname: "Rising Wing" },
  "Olivier Sarr": { quote: "Size gives you options.", nickname: "Rising Big" },
  "Olivier-Maxence Prosper": { quote: "Defensive upside changes the future.", nickname: "Rising Forward" },
  "Omer Yurtseven": { quote: "Own the glass.", nickname: "The Big Turk" },
  "Onyeka Okongwu": { quote: "Protect the paint, finish the play.", nickname: "OO" },
  "Orlando Robinson": { quote: "Keep the interior solid.", nickname: "Rising Big" },
  "Oscar Tshiebwe": { quote: "Rebounding is desire made visible.", nickname: "The Beast" },
  "Oso Ighodaro": { quote: "Smart bigs see the whole floor.", nickname: "Rising Big" },
  "Ousmane Dieng": { quote: "Potential needs patience.", nickname: "Rising Wing" },
  "P.J. Washington": { quote: "Two-way impact travels.", nickname: "PJ" },
  "PJ Hall": { quote: "Strength creates second chances.", nickname: "Rising Forward" },
  "Pacôme Dadiet": { quote: "The ceiling is still rising.", nickname: "Rising Wing" },
  "Paolo Banchero": { quote: "Power creates the advantage.", nickname: "Paolo" },
  "Pascal Siakam": { quote: "Keep moving forward.", nickname: "Spicy P" },
  "Pat Connaughton": { quote: "Every role matters.", nickname: "Patty" },
  "Pat Spencer": { quote: "Adaptation is an advantage.", nickname: "The Utility" },
  "Patrick Baldwin Jr.": { quote: "The jumper gives the game space.", nickname: "PBJ" },
  "Patrick Williams": { quote: "Defensive versatility creates value.", nickname: "P-Will" },
  "Paul George": { quote: "Smooth is a weapon.", nickname: "PG-13" },
  "Paul Reed": { quote: "Chaos creates second chances.", nickname: "Bball Paul" },
  "Payton Pritchard": { quote: "Tiny guard, huge confidence.", nickname: "Fast PP" },
  "Payton Sandfort": { quote: "The shot travels.", nickname: "Rising Shooter" },
  "Pelle Larsson": { quote: "Smart play scales.", nickname: "Rising Wing" },
  "Pete Nance": { quote: "Keep the floor balanced.", nickname: "Rising Big" },
  "Peyton Watson": { quote: "Length becomes dangerous in space.", nickname: "Rising Wing" },

  // ── Q–T ──
  "Quentin Grimes": { quote: "Let the shot come naturally.", nickname: "QG" },
  "Quenton Jackson": { quote: "Attack the opening.", nickname: "Rising Guard" },
  "Quinten Post": { quote: "Size with a shooting touch.", nickname: "Rising Big" },
  "RJ Barrett": { quote: "Attack with confidence.", nickname: "RJ" },
  "Rasheer Fleming": { quote: "Length creates defensive possibilities.", nickname: "Rising Forward" },
  "RayJ Dennis": { quote: "Control the pace.", nickname: "Rising Guard" },
  "Rayan Rupert": { quote: "Defense gives potential a path.", nickname: "Rising Wing" },
  "Reed Sheppard": { quote: "See the game before it happens.", nickname: "The General" },
  "Riley Minix": { quote: "Keep building.", nickname: "Rising Forward" },
  "Rob Dillingham": { quote: "Speed changes everything.", nickname: "Dilly" },
  "Robert Williams": { quote: "Own the airspace.", nickname: "Time Lord" },
  "Rocco Zikarsky": { quote: "The ceiling is literally enormous.", nickname: "Rising Big" },
  "Ron Harper Jr.": { quote: "Build your own chapter.", nickname: "Young Hawk" },
  "Ron Holland": { quote: "Pressure reveals competitors.", nickname: "Rising Wing" },
  "Royce O'Neale": { quote: "Do the work that wins.", nickname: "Royce" },
  "Rudy Gobert": { quote: "The paint has a guardian.", nickname: "Stifle Tower" },
  "Rui Hachimura": { quote: "Strength and touch travel together.", nickname: "Rui" },
  "Russell Westbrook": { quote: "Play every possession like it's your last.", nickname: "Brodie" },
  "Ryan Dunn": { quote: "Defense is the beginning.", nickname: "Rising Stopper" },
  "Ryan Kalkbrenner": { quote: "Protect the rim with purpose.", nickname: "Rising Big" },
  "Ryan Nembhard": { quote: "Vision turns into opportunity.", nickname: "Rising Guard" },
  "Ryan Rollins": { quote: "The next level rewards patience.", nickname: "Rising Guard" },
  "Saddiq Bey": { quote: "Stay ready for the clean look.", nickname: "Saddiq" },
  "Sam Hauser": { quote: "One release can change a game.", nickname: "The Sniper" },
  "Sam Merrill": { quote: "Never stop shooting.", nickname: "The Marksman" },
  "Sandro Mamukelashvili": { quote: "Skill creates unexpected angles.", nickname: "Mamu" },
  "Santi Aldama": { quote: "Modern size creates modern problems.", nickname: "Santi" },
  "Scoot Henderson": { quote: "Speed meets ambition.", nickname: "Scoot" },
  "Scottie Barnes": { quote: "Do a little of everything.", nickname: "Scottie" },
  "Scotty Pippen Jr.": { quote: "Legacy gives you a starting line.", nickname: "SPJ" },
  "Sean Pedulla": { quote: "The next opportunity is yours.", nickname: "Rising Guard" },
  "Seth Curry": { quote: "The shot speaks for itself.", nickname: "Chef's Bloodline" },
  "Shaedon Sharpe": { quote: "The sky is still the limit.", nickname: "Shae" },
  "Shai Gilgeous-Alexander": { quote: "Control the pace. Own the moment.", nickname: "SGA" },
  "Sharife Cooper": { quote: "Quickness creates windows.", nickname: "Rising Guard" },
  "Sidy Cissoko": { quote: "The tools are still developing.", nickname: "Rising Wing" },
  "Simone Fontecchio": { quote: "Stay ready from deep.", nickname: "The Italian Sniper" },
  "Sion James": { quote: "Defense makes opportunity.", nickname: "Rising Wing" },
  "Skal Labissière": { quote: "The talent is still there.", nickname: "Rising Big" },
  "Spencer Jones": { quote: "Keep the jumper ready.", nickname: "Rising Wing" },
  "Stanley Umude": { quote: "Make every minute count.", nickname: "Rising Wing" },
  "Stephen Curry": { quote: "Change the game. Then change it again.", nickname: "Chef Curry" },
  "Stephon Castle": { quote: "The future starts with defense.", nickname: "Rising Guard" },
  "Steven Adams": { quote: "Some problems are solved with strength.", nickname: "Aquaman" },
  "Svi Mykhailiuk": { quote: "Leave no open shot unused.", nickname: "Svi" },
  "T.J. McConnell": { quote: "Small guard. Huge impact.", nickname: "T.J." },
  "Taelon Peter": { quote: "The next chapter is unwritten.", nickname: "Rising Prospect" },
  "Taj Gibson": { quote: "Experience never leaves the game.", nickname: "Taj" },
  "Tari Eason": { quote: "Energy creates chaos.", nickname: "The Pest" },
  "Taurean Prince": { quote: "Let the jumper travel.", nickname: "TP" },
  "Taylor Hendricks": { quote: "Length gives the future shape.", nickname: "Rising Forward" },
  "Terance Mann": { quote: "Do every job that matters.", nickname: "T-Mann" },
  "Terrence Shannon Jr.": { quote: "Speed creates the advantage.", nickname: "Rising Wing" },
  "Thanasis Antetokounmpo": { quote: "Bring the energy.", nickname: "Thanasty" },
  "Thomas Bryant": { quote: "Big bodies finish plays.", nickname: "TB" },
  "Tidjane Salaün": { quote: "Potential grows in silence.", nickname: "Rising Forward" },
  "Tim Hardaway Jr.": { quote: "The jumper can heat up instantly.", nickname: "Timmy" },
  "Tobias Harris": { quote: "Stay smooth under pressure.", nickname: "Tobias" },
  "Toby Okani": { quote: "Keep building the complete game.", nickname: "Rising Wing" },
  "Tolu Smith": { quote: "Own the interior.", nickname: "Rising Big" },
  "Tony Bradley": { quote: "Size creates second chances.", nickname: "Rising Big" },
  "Tosan Evbuomwan": { quote: "Versatility gives you a future.", nickname: "Rising Forward" },
  "Toumani Camara": { quote: "Defense gives everything else a chance.", nickname: "Rising Wing" },
  "Trae Young": { quote: "Range changes the rules.", nickname: "Ice Trae" },
  "Trayce Jackson-Davis": { quote: "Finish every play above the rim.", nickname: "TJD" },
  "Tre Johnson": { quote: "Pure scoring travels.", nickname: "Rising Scorer" },
  "Tre Jones": { quote: "Keep the offense organized.", nickname: "Baby Joe" },
  "Tre Mann": { quote: "Confidence creates freedom.", nickname: "Tre" },
  "Tre Scott": { quote: "Stay ready for the opportunity.", nickname: "Rising Wing" },
  "Trendon Watford": { quote: "Versatility keeps you on the floor.", nickname: "Rising Forward" },
  "Trentyn Flowers": { quote: "The tools are there. The time is now.", nickname: "Rising Wing" },
  "Trevor Keels": { quote: "Keep attacking the next level.", nickname: "Rising Guard" },
  "Trey Alexander": { quote: "Make every possession matter.", nickname: "Rising Guard" },
  "Trey Jemison": { quote: "Own your space inside.", nickname: "Rising Big" },
  "Trey Murphy III": { quote: "Shooters change geometry.", nickname: "Trey Murphy" },
  "Tristan Da Silva": { quote: "Smooth decisions create open space.", nickname: "Rising Forward" },
  "Tristan Enaruna": { quote: "The next step starts with patience.", nickname: "Rising Wing" },
  "Tristan Vukcevic": { quote: "Skill gives size another dimension.", nickname: "Rising Big" },
  "Tristen Newton": { quote: "Make the right play.", nickname: "Rising Guard" },

  // ── T–Z ──
  "Ty Jerome": { quote: "Make the smart play.", nickname: "Ty" },
  "TyTy Washington Jr.": { quote: "Keep building the confidence.", nickname: "TyTy" },
  "Tyler Burton": { quote: "Earn the next opportunity.", nickname: "Rising Wing" },
  "Tyler Herro": { quote: "Shot makers don't fear the moment.", nickname: "Herro" },
  "Tyler Kolek": { quote: "See the pass before it exists.", nickname: "The Magician" },
  "Tyler Smith": { quote: "Keep turning tools into production.", nickname: "Rising Forward" },
  "Tyrese Martin": { quote: "Stay ready on both ends.", nickname: "Rising Wing" },
  "Tyrese Maxey": { quote: "Speed turns confidence into chaos.", nickname: "The Franchise" },
  "Tyrese Proctor": { quote: "Control the game from the backcourt.", nickname: "Rising Guard" },
  "Tyson Etienne": { quote: "Never hesitate.", nickname: "Rising Scorer" },
  "Tyus Jones": { quote: "Take care of the game.", nickname: "Tyus Stones" },
  "VJ Edgecombe": { quote: "Explosiveness creates the first advantage.", nickname: "Rising Star" },
  "Victor Wembanyama": { quote: "The future learned how to block shots.", nickname: "Wemby" },
  "Vince Williams Jr.": { quote: "Do everything that winning requires.", nickname: "Rising Wing" },
  "Vladislav Goldin": { quote: "Size becomes dangerous when paired with touch.", nickname: "Rising Big" },
  "Vít Krejčí": { quote: "Make every possession count.", nickname: "Rising Guard" },
  "Walker Kessler": { quote: "Protect the house.", nickname: "The Wall" },
  "Walter Clayton": { quote: "Big shots belong to fearless guards.", nickname: "Rising Scorer" },
  "Wendell Carter Jr.": { quote: "Control the glass. Control the paint.", nickname: "WCJ" },
  "Wendell Moore Jr.": { quote: "Patience creates opportunity.", nickname: "Rising Wing" },
  "Will Richard": { quote: "Shooters always have a place.", nickname: "Rising Shooter" },
  "Will Riley": { quote: "The future is already moving.", nickname: "Rising Wing" },
  "Xavier Tillman Sr.": { quote: "Winning plays don't need applause.", nickname: "X" },
  "Yang Hansen": { quote: "The next generation is getting taller.", nickname: "Rising Big" },
  "Yanic Konan Niederhäuser": { quote: "The tools are still developing.", nickname: "Rising Big" },
  "Yuki Kawamura": { quote: "Speed and vision beat size.", nickname: "Rising Guard" },
  "Yves Missi": { quote: "Athleticism changes the interior.", nickname: "Rising Big" },
  "Zaccharie Risacher": { quote: "The future wears a smooth jumper.", nickname: "Rising Star" },
  "Zach Collins": { quote: "Big men can create too.", nickname: "Zach" },
  "Zach Edey": { quote: "Some advantages are seven feet tall.", nickname: "The Tower" },
  "Zach LaVine": { quote: "Rise above the rim.", nickname: "Flight 8" },
  "Zeke Nnaji": { quote: "Keep attacking the next level.", nickname: "Rising Big" },
  "Ziaire Williams": { quote: "The next leap starts with confidence.", nickname: "Rising Wing" },
  "Zion Williamson": { quote: "Power changes the laws of gravity.", nickname: "Zion" },
  "Zyon Pullin": { quote: "Every level is another opportunity.", nickname: "Rising Guard" },
}

/**
 * Curated profiles keyed by NORMALIZED name for fast, accent-insensitive lookup.
 * Built once at module load from RAW_PROFILES.
 */
const PROFILE_LOOKUP: Map<string, PlayerProfile> = new Map(
  Object.entries(RAW_PROFILES).map(([name, profile]) => [normalizePlayerName(name), profile])
)

/**
 * Look up a curated profile for a player by name. Returns undefined when the
 * player isn't in the curated list (caller should fall back to generic
 * generation).
 */
export function getPlayerProfile(playerName: string | null | undefined): PlayerProfile | undefined {
  if (!playerName) return undefined
  return PROFILE_LOOKUP.get(normalizePlayerName(playerName))
}
