-- Update curated player signatures (display quote) and player_class (nickname)
-- directly on the rankings table so they show immediately, without waiting for
-- the next ranking-generation run.
--
-- signature   = the italic display quote
-- player_class = the nickname / moniker
--
-- Matched case-insensitively on player_name. Rows for players not listed here
-- keep their existing (score-derived) values.

UPDATE public.nba_player_rankings AS r
SET signature = v.quote, player_class = v.nickname
FROM (VALUES
  ('A.J. Green', 'Stay ready. Your moment always comes.', 'The Veteran'),
  ('A.J. Lawson', 'Speed turns opportunity into impact.', 'The Flyer'),
  ('AJ Johnson', 'The upside is only beginning.', 'Rising Prospect'),
  ('Aaron Gordon', 'Explosiveness changes everything.', 'AG'),
  ('Aaron Holiday', 'Small details. Big moments.', 'Mr. Reliable'),
  ('Aaron Nesmith', 'Shoot without hesitation. Defend without compromise.', 'The Sniper'),
  ('Aaron Wiggins', 'Quiet production speaks loudest.', 'A-Wiggs'),
  ('Ace Bailey', 'Talent gets attention. Growth earns respect.', 'The Ace'),
  ('Adama-Alpha Bal', 'The next chapter is waiting.', 'Rising Guard'),
  ('Adem Bona', 'Bring force to every possession.', 'The Enforcer'),
  ('Adou Thiero', 'Power becomes dangerous when refined.', 'The Tank'),
  ('Ajay Mitchell', 'Control the game before it controls you.', 'The Maestro'),
  ('Al Horford', 'Experience never goes out of style.', 'Big Al'),
  ('Alex Antetokounmpo', 'Build your own name.', 'The Antetokounmpo'),
  ('Alex Caruso', 'Effort is a skill too.', 'Bald Eagle'),
  ('Alex Morales', 'Potential means nothing without patience.', 'Rising Prospect'),
  ('Alex Sarr', 'Length creates possibilities.', 'The Tower'),
  ('Alijah Martin', 'Keep climbing until they remember your name.', 'Rising Wing'),
  ('Alondes Williams', 'Attack every opening.', 'The Aggressor'),
  ('Alperen Şengün', 'Creativity has no position.', 'Turkish Delight'),
  ('Amari Williams', 'Make every possession count.', 'The Anchor'),
  ('Amen Thompson', 'Athleticism is only the beginning.', 'The Blur'),
  ('Amir Coffey', 'Patience creates consistency.', 'The Smooth Operator'),
  ('Andersson Garcia', 'The work speaks before the spotlight does.', 'Rising Forward'),
  ('Andre Drummond', 'Own the glass. Own the paint.', 'Big Penguin'),
  ('Andre Jackson Jr.', 'Defense travels everywhere.', 'The Glue'),
  ('Andrew Nembhard', 'Steady hands win chaotic games.', 'The General'),
  ('Andrew Wiggins', 'Silence the noise. Let the game answer.', 'Maple Jordan'),
  ('Anfernee Simons', 'One shot can change the rhythm.', 'Ant'),
  ('Anthony Black', 'See the game before it happens.', 'AB'),
  ('Anthony Davis', 'Defense starts with presence.', 'The Brow'),
  ('Anthony Edwards', 'Fear is fuel.', 'Ant-Man'),
  ('Anthony Gill', 'Stay prepared. Stay useful.', 'The Professional'),
  ('Antonio Reeves', 'Confidence grows one bucket at a time.', 'The Scorer'),
  ('Ariel Hukporti', 'The foundation is already here.', 'Rising Big'),
  ('Asa Newell', 'Potential becomes power through repetition.', 'Rising Big'),
  ('Ausar Thompson', 'Impact doesn''t always need a jumper.', 'The Disruptor'),
  ('Austin Reaves', 'Make them remember the fourth quarter.', 'AR15'),
  ('Ayo Dosunmu', 'Speed, strength, instinct.', 'The Accelerator'),
  ('Bam Adebayo', 'Do everything. Guard everyone.', 'Bam'),
  ('Baylor Scheierman', 'One clean look can change everything.', 'The Marksman'),
  ('Ben Saraf', 'The ceiling is still moving.', 'Rising Guard'),
  ('Ben Sheppard', 'Play smart. Play hard.', 'The Grinder'),
  ('Bennedict Mathurin', 'Aggression creates opportunity.', 'Benny'),
  ('Bez Mbeng', 'Every great run starts somewhere.', 'Rising Prospect'),
  ('Bilal Coulibaly', 'Length. Speed. Untapped potential.', 'Bilal'),
  ('Bismack Biyombo', 'Protect the paint. Protect the standard.', 'The Mountain'),
  ('Blake Hinson', 'Let the jumper speak.', 'The Gunner'),
  ('Blake Wesley', 'Attack the gaps.', 'The Blur'),
  ('Bobby Portis', 'Energy changes the temperature.', 'Bobby Buckets'),
  ('Bobi Klintman', 'Raw tools become weapons with time.', 'Rising Forward'),
  ('Bogdan Bogdanović', 'Cold-blooded when the game heats up.', 'Bogi'),
  ('Bones Hyland', 'Chaos has a rhythm.', 'Bones'),
  ('Bradley Beal', 'When the game slows, attack.', 'Big Panda'),
  ('Branden Carlson', 'Size creates an advantage. Skill makes it dangerous.', 'The Tower'),
  ('Brandin Podziemski', 'Play bigger than the box score.', 'Podz'),
  ('Brandon Clarke', 'Elevate above the defense.', 'BC'),
  ('Brandon Ingram', 'Smooth never goes out of style.', 'Slenderman'),
  ('Brandon Miller', 'Quiet confidence, loud results.', 'B-Mill'),
  ('Brandon Williams', 'The opportunity belongs to whoever takes it.', 'Rising Guard'),
  ('Brice Sensabaugh', 'Let the scoring come naturally.', 'The Bucket'),
  ('Bronny James', 'The name opens the door. The work keeps it open.', 'Bronny'),
  ('Brook Lopez', 'Protect the rim. Stretch the floor.', 'Splash Mountain'),
  ('Brooks Barnhizer', 'Motor matters.', 'Rising Wing'),
  ('Bruce Brown', 'Do the little things that win.', 'Playoff B'),
  ('Bryce McGowens', 'Patience turns potential into production.', 'Rising Scorer'),
  ('Bub Carrington', 'Young legs. Veteran instincts.', 'Bub'),
  ('Buddy Boeheim', 'Let it fly.', 'The Shooter'),
  ('Buddy Hield', 'Never hesitate from deep.', 'Buddy Buckets'),
  ('CJ Huntley', 'The next opportunity starts today.', 'Rising Prospect'),
  ('CJ McCollum', 'Craft beats chaos.', 'Three-J'),
  ('Cade Cunningham', 'Control the game. Control the pace.', 'Cade'),
  ('Caleb Houstan', 'Make the open shot count.', 'The Sniper'),
  ('Caleb Love', 'Confidence travels.', 'CL'),
  ('Caleb Martin', 'Built for the big stage.', 'Caleb'),
  ('Cam Christie', 'The jumper is only the beginning.', 'Rising Shooter'),
  ('Cam Spencer', 'Find the shot. Take the shot.', 'Cam'),
  ('Cam Thomas', 'Buckets don''t need permission.', 'Mr. Bucket'),
  ('Cam Whitmore', 'Power through the hesitation.', 'Cam'),
  ('Cameron Johnson', 'A clean release changes everything.', 'Cam Johnson'),
  ('Cameron Payne', 'Speed the game up.', 'Campaign'),
  ('Caris LeVert', 'Versatility keeps doors open.', 'Caris'),
  ('Carter Bryant', 'Two-way potential is dangerous.', 'Rising Wing'),
  ('Cason Wallace', 'Pressure creates mistakes. Be the pressure.', 'C-Wall'),
  ('Cedric Coward', 'Potential becomes real when the game slows down.', 'The Sleeper'),
  ('Chaney Johnson', 'Keep stacking the pieces.', 'Rising Forward'),
  ('Charles Bassey', 'Protect the paint with purpose.', 'The Anchor'),
  ('Chaz Lanier', 'Shooters change games quickly.', 'The Gunner'),
  ('Chet Holmgren', 'Skill makes size unfair.', 'Chet'),
  ('Chris Boucher', 'Bring length to every possession.', 'Slim Reaper'),
  ('Chris Livingston', 'Patience is part of the process.', 'Rising Wing'),
  ('Chris Mañon', 'The next opportunity is yours.', 'Rising Prospect'),
  ('Chris Paul', 'Command the game.', 'CP3'),
  ('Chris Youngblood', 'Keep building the next level.', 'Rising Prospect'),
  ('Christian Braun', 'Defense travels. Confidence follows.', 'CB'),
  ('Christian Koloko', 'Protect the rim.', 'The Rim Protector'),
  ('Chucky Hepburn', 'The floor is yours.', 'Rising Guard'),
  ('Clint Capela', 'Own the paint.', 'The Lob Monster'),
  ('Coby White', 'Let the speed take over.', 'White Lightning'),
  ('Cody Martin', 'Versatility is value.', 'Cody'),
  ('Cody Williams', 'The ceiling is still rising.', 'Rising Wing'),
  ('Colby Jones', 'Keep the game simple.', 'The Connector'),
  ('Cole Anthony', 'Play with your heart on every possession.', 'Cole World'),
  ('Colin Castleton', 'Big bodies make big problems.', 'Rising Big'),
  ('Collin Gillespie', 'IQ can beat athleticism.', 'The Floor General'),
  ('Collin Murray-Boyles', 'Strength travels.', 'Rising Forward'),
  ('Collin Sexton', 'Bring the speed every night.', 'Young Bull'),
  ('Cooper Flagg', 'Defense starts the story. Everything else follows.', 'The Flag'),
  ('Corey Kispert', 'One inch of daylight is enough.', 'The Sharpshooter'),
  ('Cormac Ryan', 'Stay ready for the moment.', 'The Shooter'),
  ('Craig Porter Jr.', 'Control the tempo.', 'The Conductor'),
  ('Curtis Jones', 'Every possession is another opportunity.', 'Rising Guard'),
  ('D''Angelo Russell', 'Confidence makes impossible passes look easy.', 'DLo'),
  ('DaQuan Jeffries', 'Stay ready. Stay dangerous.', 'The Wing'),
  ('DaRon Holmes', 'The paint belongs to the fearless.', 'Rising Big'),
  ('Daeqwon Plowden', 'Keep attacking the opportunity.', 'Rising Wing'),
  ('Dalano Banton', 'Size changes the angles.', 'The Long Guard'),
  ('Dalen Terry', 'Energy never goes out of style.', 'DT'),
  ('Dalton Knecht', 'Catch. Rise. Fire.', 'The Marksman'),
  ('Daniel Gafford', 'Meet the rim above the rim.', 'DG'),
  ('Daniss Jenkins', 'The next play is always yours.', 'Rising Guard'),
  ('Danny Wolf', 'Smart players see space differently.', 'The Big Facilitator'),
  ('Dario Šarić', 'Skill travels across generations.', 'The Homie'),
  ('Dariq Whitehead', 'The talent is still there.', 'Rising Wing'),
  ('Darius Brown II', 'Build momentum, one possession at a time.', 'Rising Guard'),
  ('Darius Garland', 'Small space. Big creation.', 'DG'),
  ('David Jones García', 'Aggression can open every door.', 'Rising Wing'),
  ('David Roddy', 'Strength creates its own lane.', 'Showtime'),
  ('Davion Mitchell', 'Pressure starts at half court.', 'Off Night'),
  ('Day''Ron Sharpe', 'Own the rebound. Own the possession.', 'The Beast'),
  ('De''Aaron Fox', 'Speed becomes unstoppable when controlled.', 'Swipa'),
  ('De''Andre Hunter', 'Patience turns defense into offense.', 'The Hunter'),
  ('De''Anthony Melton', 'Disruption creates opportunity.', 'Mr. Do Something'),
  ('DeAndre Jordan', 'Protect the rim. Lead the room.', 'DJ'),
  ('DeJon Jarreau', 'Make every possession uncomfortable.', 'The Pest'),
  ('DeMar DeRozan', 'Midrange is an art.', 'Deebo'),
  ('Dean Wade', 'Do your job every night.', 'The Utility'),
  ('Deandre Ayton', 'Power starts with presence.', 'DominAyton'),
  ('Dejounte Murray', 'See everything. Control everything.', 'Baby Joker'),
  ('Deni Avdija', 'Versatility makes the game easier.', 'Deni'),
  ('Dennis Schröder', 'Push the pace.', 'Dennis the Menace'),
  ('Dereck Lively II', 'Verticality changes the paint.', 'DLive'),
  ('Derik Queen', 'Inside skill creates outside problems.', 'The Queen'),
  ('Derrick Jones Jr.', 'The sky is never too high.', 'Airplane Mode'),
  ('Derrick White', 'Do everything right.', 'The Buffalo'),
  ('Desmond Bane', 'Strength turns separation into certainty.', 'Bane'),
  ('Devin Booker', 'Pure scoring is an art.', 'Book'),
  ('Devin Carter', 'Defense travels with you.', 'Rising Guard'),
  ('Devin Vassell', 'Smooth scoring under pressure.', 'Vassell'),
  ('Dillon Brooks', 'Make every matchup personal.', 'The Villain'),
  ('Dillon Jones', 'Attack with purpose.', 'Rising Wing'),
  ('Domantas Sabonis', 'The offense begins with the big man.', 'Domas'),
  ('Dominick Barlow', 'Keep growing into your game.', 'Rising Forward'),
  ('Donovan Clingan', 'The paint has a new owner.', 'The Big Fella'),
  ('Donovan Mitchell', 'Light the arena.', 'Spida'),
  ('Donte DiVincenzo', 'Do the dirty work and hit the big shot.', 'The Big Ragu'),
  ('Dorian Finney-Smith', 'Versatility survives every matchup.', 'DFS'),
  ('Doug McDermott', 'Never waste an open look.', 'Dougie McBuckets'),
  ('Drake Powell', 'The future moves fast.', 'Rising Wing'),
  ('Draymond Green', 'Impact isn''t always measured in points.', 'Day-Day'),
  ('Drew Eubanks', 'Bring the force inside.', 'D-Block'),
  ('Drew Peterson', 'Make the smart play.', 'The Connector'),
  ('Drew Timme', 'Toughness travels.', 'The Big Fundamental'),
  ('Dru Smith', 'Stay ready for every assignment.', 'The Specialist'),
  ('Duncan Robinson', 'One shot can bend a defense.', 'Duncan'),
  ('Duop Reath', 'Size plus touch changes the equation.', 'The Stretch Big'),
  ('Dwight Powell', 'Consistency is a skill.', 'DP'),
  ('Dylan Cardwell', 'Own the glass.', 'Rising Big'),
  ('Dylan Harper', 'Vision, size, control.', 'The Young General'),
  ('Dyson Daniels', 'Make every possession difficult.', 'The Great Barrier'),
  ('E.J. Liddell', 'Strength gives the game a foundation.', 'Rising Forward'),
  ('Egor Dëmin', 'The ceiling is still out of sight.', 'The Russian Prospect'),
  ('Elijah Harkless', 'Defense creates your next opportunity.', 'The Stopper'),
  ('Emanuel Miller', 'Toughness travels.', 'Rising Forward'),
  ('Enrique Freeman', 'Rebounding is a mentality.', 'The Hustler'),
  ('Eric Gordon', 'Shooters never stop being dangerous.', 'EJ'),
  ('Ethan Thompson', 'Keep earning the next possession.', 'Rising Guard'),
  ('Evan Mobley', 'Length, intelligence, control.', 'Mobley'),
  ('Franz Wagner', 'Smooth decisions create hard problems.', 'The Prince'),
  ('GG Jackson II', 'Potential gets loud when confidence arrives.', 'GG'),
  ('Gabe Vincent', 'Big moments need calm players.', 'Gabe'),
  ('Garrett Temple', 'Experience makes the game slower.', 'The Elder'),
  ('Garrison Mathews', 'One open look is all you need.', 'Garrison'),
  ('Gary Harris', 'Stay ready on both ends.', 'G-Money'),
  ('Gary Payton II', 'Defense is an attitude.', 'Young Glove'),
  ('Gary Trent Jr.', 'Let the jumper decide.', 'GTJ'),
  ('Giannis Antetokounmpo', 'Keep improving until impossible looks ordinary.', 'The Greek Freak'),
  ('Goga Bitadze', 'Protect the paint with patience.', 'Goga'),
  ('Gradey Dick', 'The jumper travels anywhere.', 'Gradey'),
  ('Grant Nelson', 'Keep turning potential into production.', 'Rising Forward'),
  ('Grant Williams', 'Make every matchup uncomfortable.', 'Batman'),
  ('Grayson Allen', 'Don''t hesitate. Don''t apologize.', 'The Accountant'),
  ('Guerschon Yabusele', 'Power belongs in the modern game.', 'The Dancing Bear'),
  ('Gui Santos', 'The upside is only beginning.', 'Rising Wing'),
  ('Harrison Barnes', 'Consistency is its own superpower.', 'HB'),
  ('Harrison Ingram', 'Effort gives talent a foundation.', 'Rising Wing'),
  ('Hayden Gray', 'Every level starts with belief.', 'Rising Prospect'),
  ('Haywood Highsmith', 'Defense creates a career.', 'H'),
  ('Herbert Jones', 'Make the game uncomfortable.', 'The Stinger'),
  ('Hugo González', 'The tools are already there.', 'Rising Star'),
  ('Hunter Dickinson', 'Own the interior.', 'The Big Cat'),
  ('Hunter Sallis', 'Let your confidence catch up to your talent.', 'Rising Guard'),
  ('Hunter Tyson', 'Shooters punish hesitation.', 'The Sniper'),
  ('Immanuel Quickley', 'Pace is a weapon.', 'IQ'),
  ('Isaac Jones', 'Keep attacking the rim.', 'Rising Big'),
  ('Isaac Okoro', 'Defense is the foundation.', 'The Lock'),
  ('Isaiah Collier', 'Fast decisions create fast offense.', 'Rising Guard'),
  ('Isaiah Crawford', 'Make your versatility matter.', 'Rising Wing'),
  ('Isaiah Hartenstein', 'Rebounding is positioning and desire.', 'The Big Screen'),
  ('Isaiah Jackson', 'Protect the rim, attack the glass.', 'IJ'),
  ('Isaiah Joe', 'One shot changes everything.', 'Joe Cool'),
  ('Isaiah Livers', 'Keep finding your rhythm.', 'Rising Wing'),
  ('Isaiah Stevens', 'IQ makes speed irrelevant.', 'The Floor General'),
  ('Isaiah Stewart', 'Bring the fight inside.', 'Beef Stew'),
  ('Ivica Zubac', 'The paint belongs to the relentless.', 'Zu'),
  ('JD Davison', 'Pressure creates opportunity.', 'Rising Guard'),
  ('Ja Morant', 'Gravity can''t stop the leap.', 'G12'),
  ('Ja''Kobe Walter', 'Shooters grow into stars.', 'Rising Scorer'),
  ('Jabari Smith Jr.', 'Height plus skill changes the geometry.', 'Jabari'),
  ('Jabari Walker', 'Let the work build the confidence.', 'Rising Forward'),
  ('Jacob Toppin', 'Attack the sky.', 'Rising Flyer'),
  ('Jaden Hardy', 'Confidence turns creation into scoring.', 'J-Hardy'),
  ('Jaden Ivey', 'Speed breaks defenses.', 'JI'),
  ('Jaden McDaniels', 'Length makes every possession harder.', 'J-Mac'),
  ('Jae''Sean Tate', 'Do the work nobody notices.', 'The Tough One'),
  ('Jahmai Mashack', 'Defense opens doors.', 'Rising Guard'),
  ('Jahmir Young', 'Control the pace.', 'The Commander'),
  ('Jahmyl Telfort', 'Keep climbing.', 'Rising Wing'),
  ('Jaime Jaquez Jr.', 'Old-school toughness in a new era.', 'Triple J'),
  ('Jake LaRavia', 'Play every role with purpose.', 'The Utility'),
  ('Jakob Poeltl', 'Own the paint without forcing it.', 'The Big Austrian'),
  ('Jalen Brunson', 'Heart beats size.', 'Young Star'),
  ('Jalen Duren', 'Power your way through the paint.', 'JD'),
  ('Jalen Green', 'The rim is never too far.', 'JG4'),
  ('Jalen Johnson', 'Versatility makes the game simple.', 'JJ'),
  ('Jalen Pickett', 'Craft beats chaos.', 'The Technician'),
  ('Jalen Slawson', 'Keep building the complete game.', 'Rising Forward'),
  ('Jalen Smith', 'Bring size with skill.', 'Stix'),
  ('Jalen Suggs', 'Pressure every possession.', 'Suggs'),
  ('Jalen Williams', 'Efficiency makes greatness look easy.', 'JDub'),
  ('Jalen Wilson', 'Keep earning every minute.', 'Rising Wing'),
  ('Jamal Cain', 'Energy creates opportunity.', 'Rising Wing'),
  ('Jamal Murray', 'Save your best for the brightest lights.', 'Blue Arrow'),
  ('Jamal Shead', 'Defense starts with attitude.', 'Rising Guard'),
  ('Jamaree Bouyea', 'Keep making the next play.', 'Rising Guard'),
  ('James Harden', 'Slow the game down. Own it.', 'The Beard'),
  ('James Wiseman', 'The tools are too big to ignore.', 'Big Wise'),
  ('Jamir Watkins', 'Explosiveness creates separation.', 'Rising Wing'),
  ('Jamison Battle', 'Let your shot travel.', 'JB'),
  ('Jarace Walker', 'Strength creates versatility.', 'Rising Forward'),
  ('Jared McCain', 'Confidence is contagious.', 'McNasty'),
  ('Jaren Jackson Jr.', 'Protect the rim. Stretch the floor.', 'Triple J'),
  ('Jarred Vanderbilt', 'Defense is effort made visible.', 'Vando'),
  ('Jarrett Allen', 'Protect everything above the rim.', 'Fro'),
  ('Jase Richardson', 'The next generation arrives fast.', 'Rising Guard'),
  ('Javon Small', 'Every possession is another chance.', 'Rising Guard'),
  ('Javonte Cooke', 'Keep chasing the next level.', 'Rising Prospect'),
  ('Javonte Green', 'Athleticism creates second chances.', 'JG'),
  ('Jaxson Hayes', 'Meet the rim at the top.', 'Jaxson'),
  ('Jay Huff', 'Seven feet changes the equation.', 'Rising Big'),
  ('Jaylen Brown', 'Strength. Purpose. Progress.', 'JB'),
  ('Jaylen Clark', 'Defense is identity.', 'The Lock'),
  ('Jaylen Wells', 'Let the game come to you.', 'Rising Wing'),
  ('Jaylin Williams', 'Make the smart play.', 'J-Will'),
  ('Jaylon Tyson', 'Every role can become a weapon.', 'Rising Wing'),
  ('Jayson Kent', 'Keep building the foundation.', 'Rising Forward'),
  ('Jayson Tatum', 'Don''t chase greatness. Become it.', 'JT'),
  ('Jeff Green', 'Experience gives you another gear.', 'Uncle Jeff'),
  ('Jerami Grant', 'Length becomes lethal with confidence.', 'Jerami'),
  ('Jeremiah Fears', 'Fear is just another word for opportunity.', 'Rising Guard'),
  ('Jeremiah Robinson-Earl', 'Do the little things that matter.', 'JRE'),
  ('Jeremy Sochan', 'Chaos can be creativity.', 'Young Wolf'),
  ('Jericho Sims', 'The rim is a meeting point.', 'Rising Big'),
  ('Jett Howard', 'One clean release changes everything.', 'Jett'),
  ('Jevon Carter', 'Defend first. Everything follows.', 'Mr. 94 Feet'),
  ('Jimmy Butler', 'Work wins when talent gets tired.', 'Jimmy Buckets'),
  ('Joan Beringer', 'The tools are rare. The journey is just starting.', 'Rising Big'),
  ('Jock Landale', 'Bring toughness to the interior.', 'Jock'),
  ('Joe Ingles', 'Let experience control the game.', 'Slow Mo'),
  ('Joel Embiid', 'Trust the process. Own the moment.', 'The Process'),
  ('John Collins', 'Finish above the defense.', 'JC'),
  ('John Konchar', 'Every team needs a connector.', 'Jitty'),
  ('John Poulakidas', 'A shooter only needs one opening.', 'Rising Shooter'),
  ('John Tonje', 'Confidence turns opportunity into points.', 'Rising Scorer'),
  ('Johni Broome', 'Control the paint. Control the game.', 'Rising Big'),
  ('Johnny Furphy', 'The next level rewards patience.', 'Rising Wing'),
  ('Johnny Juzang', 'Buckets come from belief.', 'Juzang'),
  ('Jonas Valančiūnas', 'Old-school power still works.', 'JV'),
  ('Jonathan Isaac', 'Length creates defensive gravity.', 'JI'),
  ('Jonathan Kuminga', 'Raw power becomes unstoppable with polish.', 'JK'),
  ('Jonathan Mogbo', 'Athleticism creates possibilities.', 'Rising Forward'),
  ('Jordan Clarkson', 'Heat checks are part of the job.', 'JC'),
  ('Jordan Goodwin', 'Defend. Rebound. Compete.', 'Goodwin'),
  ('Jordan Hawkins', 'Never stop running.', 'Hawk'),
  ('Jordan McLaughlin', 'Control the second unit.', 'J-Mac'),
  ('Jordan Miller', 'Keep climbing through the noise.', 'Rising Wing'),
  ('Jordan Poole', 'Chaos creates highlights.', 'JP'),
  ('Jordan Walsh', 'Defense gives you a role.', 'Rising Wing'),
  ('Jose Alvarado', 'Pressure is a personality.', 'Grand Theft Alvarado'),
  ('Josh Giddey', 'See the pass before the defense.', 'Giddey'),
  ('Josh Green', 'Play fast, think faster.', 'JG'),
  ('Josh Hart', 'Winning plays don''t need a spotlight.', 'Josh Hart'),
  ('Josh Minott', 'Athleticism is a foundation.', 'Rising Wing'),
  ('Josh Oduro', 'Strength earns space.', 'Rising Big'),
  ('Josh Okogie', 'Make every scorer uncomfortable.', 'The Pest'),
  ('Jrue Holiday', 'Defense is possession control.', 'Uncle Drew'),
  ('Julian Champagnie', 'Stay ready for the corner.', 'Rising Shooter'),
  ('Julian Phillips', 'Let athleticism become consistency.', 'Rising Wing'),
  ('Julian Reese', 'Own your space.', 'Rising Big'),
  ('Julian Strawther', 'Let it fly.', 'The Shooter'),
  ('Julius Randle', 'Force your way to the finish.', 'Beyblade'),
  ('Justin Champagnie', 'Keep the pressure on.', 'Rising Wing'),
  ('Justin Edwards', 'The ceiling is high. Keep climbing.', 'Rising Wing'),
  ('Jusuf Nurkić', 'Make the paint a problem.', 'The Bosnian Beast'),
  ('KJ Simpson', 'Keep the engine running.', 'Rising Guard'),
  ('Kadary Richmond', 'Every possession has purpose.', 'Rising Guard'),
  ('Kam Jones', 'Confidence travels with the jumper.', 'Rising Guard'),
  ('Karl-Anthony Towns', 'Size, touch, range.', 'KAT'),
  ('Karlo Matković', 'Length creates another dimension.', 'Rising Big'),
  ('Kasparas Jakučionis', 'The vision is already there.', 'Rising Playmaker'),
  ('Kawhi Leonard', 'Quiet is deadly.', 'The Klaw'),
  ('Keaton Wallace', 'Stay ready. Stay steady.', 'Rising Guard'),
  ('Keegan Murray', 'The jumper changes everything.', 'Keegan'),
  ('Kel''el Ware', 'The upside starts with the tools.', 'Rising Big'),
  ('Keldon Johnson', 'Attack every opening.', 'Big Body'),
  ('Kelly Olynyk', 'Big men can create too.', 'KO'),
  ('Kelly Oubre Jr.', 'Confidence looks good in motion.', 'Tsunami Papi'),
  ('Kennedy Chandler', 'Control the pace.', 'Rising Guard'),
  ('Kenrich Williams', 'Do whatever winning requires.', 'Kenrich'),
  ('Kentavious Caldwell-Pope', 'Defend. Move. Shoot.', 'KCP'),
  ('Keon Ellis', 'Defense creates your value.', 'Rising Guard'),
  ('Keshad Johnson', 'Toughness opens doors.', 'Rising Wing'),
  ('Keshon Gilbert', 'Keep attacking the next level.', 'Rising Guard'),
  ('Kevin Durant', 'Greatness looks effortless when preparation is endless.', 'Slim Reaper'),
  ('Kevin Huerter', 'One clean look is enough.', 'Red Velvet'),
  ('Kevin Love', 'Let the experience stretch the floor.', 'K-Love'),
  ('Kevin McCullar Jr.', 'Impact doesn''t require volume.', 'Rising Wing'),
  ('Kevin Porter Jr.', 'Creation starts with confidence.', 'KPJ'),
  ('Kevon Looney', 'The little things win championships.', 'Loon'),
  ('Keyonte George', 'Let the scorer emerge.', 'Rising Guard'),
  ('Khaman Maluach', 'The ceiling begins at seven feet.', 'The Tower'),
  ('Khris Middleton', 'Calm is a weapon.', 'Khri$'),
  ('Killian Hayes', 'Control the tempo.', 'Rising Guard'),
  ('Klay Thompson', 'Sometimes one quarter is all it takes.', 'Game 6 Klay'),
  ('Kobe Brown', 'Play bigger than the moment.', 'Rising Forward'),
  ('Kobe Bufkin', 'The next jump is waiting.', 'Rising Guard'),
  ('Kobe Sanders', 'Let the next level find you ready.', 'Rising Wing'),
  ('Koby Brea', 'Never waste an open shot.', 'The Marksman'),
  ('Kon Knueppel', 'Skill travels faster than hype.', 'Rising Shooter'),
  ('Kris Dunn', 'Defense travels.', 'The Bulldog'),
  ('Kris Murray', 'Consistency becomes confidence.', 'Rising Wing'),
  ('Kristaps Porziņģis', 'Seven feet of skill changes everything.', 'The Unicorn'),
  ('Kyle Anderson', 'Slow the game down.', 'Slo Mo'),
  ('Kyle Filipowski', 'Skill makes size dangerous.', 'Flip'),
  ('Kyle Kuzma', 'Make noise with your own style.', 'Kuz'),
  ('Kyle Lowry', 'Sacrifice makes winning possible.', 'K-Low'),
  ('Kyshawn George', 'The game rewards size and patience.', 'Rising Wing'),
  ('LJ Cryer', 'Every clean look counts.', 'The Shooter'),
  ('LaMelo Ball', 'Make the impossible entertaining.', 'Melo'),
  ('Lachlan Olbrich', 'The next level starts with confidence.', 'Rising Prospect'),
  ('Landry Shamet', 'Never hesitate.', 'The Shooter'),
  ('Larry Nance Jr.', 'Athleticism runs in the family.', 'Jr.'),
  ('Lauri Markkanen', 'Seven feet of pure shooting.', 'The Finnisher'),
  ('Lawson Lovering', 'Let the foundation get stronger.', 'Rising Big'),
  ('LeBron James', 'Greatness is built for the moments that matter.', 'King James'),
  ('League Average', 'The standard everyone is measured against.', 'The Baseline'),
  ('Leaky Black', 'Defense gives you a place.', 'Rising Wing'),
  ('Leonard Miller', 'The tools are too intriguing to ignore.', 'Rising Forward'),
  ('Liam McNeeley', 'Let the jumper introduce you.', 'Rising Wing'),
  ('Lindy Waters III', 'One shot can change a game.', 'The Sniper'),
  ('Lonzo Ball', 'See the court differently.', 'Zo'),
  ('Lucas Williamson', 'Smart basketball lasts.', 'Rising Guard'),
  ('Luguentz Dort', 'Every possession is a fight.', 'Dorture Chamber'),
  ('Luka Dončić', 'Slow pace. Impossible results.', 'Luka Magic'),
  ('Luka Garza', 'Buckets come in every form.', 'The Big Bucket'),
  ('Luke Kennard', 'Leave no open shot unused.', 'The Sharpshooter'),
  ('Luke Kornet', 'Seven feet of hustle.', 'Luke'),
  ('Mac McClung', 'The spotlight belongs to whoever attacks it.', 'Mac'),
  ('Malachi Smith', 'Keep the next play simple.', 'Rising Guard'),
  ('Malaki Branham', 'Let patience become production.', 'Rising Scorer'),
  ('Malevy Leons', 'The opportunity is still unfolding.', 'Rising Forward'),
  ('Malik Monk', 'Turn energy into points.', 'Monk'),
  ('MarJon Beauchamp', 'Athleticism becomes dangerous with confidence.', 'Rising Wing'),
  ('Marcus Sasser', 'Small guard, big confidence.', 'Mighty Mouse'),
  ('Marcus Smart', 'Heart makes up for everything.', 'Cobra'),
  ('Mark Sears', 'Shooters don''t blink.', 'Rising Scorer'),
  ('Mark Williams', 'Own the paint.', 'The Big'),
  ('Markelle Fultz', 'The comeback is part of the story.', 'Kelle'),
  ('Marvin Bagley III', 'Verticality creates opportunity.', 'Bagley'),
  ('Mason Plumlee', 'Do the winning work.', 'Plumdog'),
  ('Matas Buzelis', 'The ceiling starts with imagination.', 'Rising Wing'),
  ('Matisse Thybulle', 'Steals are momentum.', 'Tisse'),
  ('Max Christie', 'The next leap starts with consistency.', 'Rising Wing'),
  ('Max Shulga', 'The game is still getting bigger.', 'Rising Guard'),
  ('Max Strus', 'No hesitation.', 'The Strus'),
  ('Maxi Kleber', 'Positionless skill has value.', 'Maxi'),
  ('Maxime Raynaud', 'Size, touch, production.', 'Rising Big'),
  ('Micah Peavy', 'Keep climbing.', 'Rising Wing'),
  ('Micah Potter', 'The shot always has a place.', 'The Stretch Big'),
  ('Michael Porter Jr.', 'Rise above the contest.', 'MPJ'),
  ('Mikal Bridges', 'Reliability is a superpower.', 'The Ironman'),
  ('Mike Conley', 'Lead without needing the spotlight.', 'Uncle Mike'),
  ('Miles Bridges', 'Bring the force every night.', 'Mile High'),
  ('Miles Kelly', 'Let the next opportunity become yours.', 'Rising Wing'),
  ('Miles McBride', 'Pressure never stops.', 'Deuce'),
  ('Mitchell Robinson', 'Protect the rim at all costs.', 'Blockinson'),
  ('Mo Bamba', 'Length changes the game.', 'Mo'),
  ('Mohamed Diawara', 'Raw tools can become special.', 'Rising Forward'),
  ('Monte Morris', 'Steady hands win games.', 'Money'),
  ('Moritz Wagner', 'Bring energy, then bring chaos.', 'Moe'),
  ('Moses Moody', 'Stay patient. Keep improving.', 'Moody'),
  ('Mouhamadou Gueye', 'The upside starts with effort.', 'Rising Forward'),
  ('Mouhamed Gueye', 'Let the tools develop.', 'Rising Big'),
  ('Moussa Cisse', 'Protect the paint with force.', 'The Anchor'),
  ('Moussa Diabaté', 'Athleticism opens the door.', 'Rising Big'),
  ('Myles Turner', 'Blocks and buckets.', 'Myles'),
  ('Myron Gardner', 'The next step belongs to the hungry.', 'Rising Forward'),
  ('N''Faly Dante', 'Own every inch of the paint.', 'The Enforcer'),
  ('Nae''Qwan Tomlin', 'Keep making the next play.', 'Rising Forward'),
  ('Naji Marshall', 'Make every matchup count.', 'Naji'),
  ('Nate Williams', 'Opportunity rewards readiness.', 'Rising Guard'),
  ('Naz Reid', 'Let the big man shoot.', 'NAZ Reid'),
  ('Neemias Queta', 'Protect the glass.', 'Rising Big'),
  ('Nic Claxton', 'Defense changes the entire floor.', 'Clax'),
  ('Nick Richards', 'Own the interior.', 'Rising Big'),
  ('Nick Smith Jr.', 'The jumper can change everything.', 'Rising Guard'),
  ('Nickeil Alexander-Walker', 'Versatility is the weapon.', 'NAW'),
  ('Nicolas Batum', 'Experience fills every gap.', 'Batman'),
  ('Nigel Hayes-Davis', 'Keep expanding the game.', 'Rising Forward'),
  ('Nikola Jokić', 'Make the difficult look effortless.', 'The Joker'),
  ('Nikola Jović', 'Size creates a different kind of skill.', 'Rising Forward'),
  ('Nikola Topić', 'See the next pass first.', 'Rising Guard'),
  ('Nikola Vučević', 'Skill from the middle changes everything.', 'Vooch'),
  ('Nique Clifford', 'Production always finds its level.', 'Rising Wing'),
  ('Noa Essengue', 'The raw tools are already rare.', 'Rising Forward'),
  ('Noah Clowney', 'Let the length do the damage.', 'Rising Big'),
  ('Noah Penda', 'Potential becomes production with time.', 'Rising Forward'),
  ('Nolan Traoré', 'Speed creates the first advantage.', 'Rising Guard'),
  ('Norchad Omier', 'Toughness starts inside.', 'Rising Big'),
  ('Norman Powell', 'Instant offense is a skill.', 'Playoff Powell'),
  ('OG Anunoby', 'Make stars work for every point.', 'OG'),
  ('Obi Toppin', 'Elevate the ordinary.', 'Obi'),
  ('Ochai Agbaji', 'Make the open shot count.', 'Rising Wing'),
  ('Olivier Sarr', 'Size gives you options.', 'Rising Big'),
  ('Olivier-Maxence Prosper', 'Defensive upside changes the future.', 'Rising Forward'),
  ('Omer Yurtseven', 'Own the glass.', 'The Big Turk'),
  ('Onyeka Okongwu', 'Protect the paint, finish the play.', 'OO'),
  ('Orlando Robinson', 'Keep the interior solid.', 'Rising Big'),
  ('Oscar Tshiebwe', 'Rebounding is desire made visible.', 'The Beast'),
  ('Oso Ighodaro', 'Smart bigs see the whole floor.', 'Rising Big'),
  ('Ousmane Dieng', 'Potential needs patience.', 'Rising Wing'),
  ('P.J. Washington', 'Two-way impact travels.', 'PJ'),
  ('PJ Hall', 'Strength creates second chances.', 'Rising Forward'),
  ('Pacôme Dadiet', 'The ceiling is still rising.', 'Rising Wing'),
  ('Paolo Banchero', 'Power creates the advantage.', 'Paolo'),
  ('Pascal Siakam', 'Keep moving forward.', 'Spicy P'),
  ('Pat Connaughton', 'Every role matters.', 'Patty'),
  ('Pat Spencer', 'Adaptation is an advantage.', 'The Utility'),
  ('Patrick Baldwin Jr.', 'The jumper gives the game space.', 'PBJ'),
  ('Patrick Williams', 'Defensive versatility creates value.', 'P-Will'),
  ('Paul George', 'Smooth is a weapon.', 'PG-13'),
  ('Paul Reed', 'Chaos creates second chances.', 'Bball Paul'),
  ('Payton Pritchard', 'Tiny guard, huge confidence.', 'Fast PP'),
  ('Payton Sandfort', 'The shot travels.', 'Rising Shooter'),
  ('Pelle Larsson', 'Smart play scales.', 'Rising Wing'),
  ('Pete Nance', 'Keep the floor balanced.', 'Rising Big'),
  ('Peyton Watson', 'Length becomes dangerous in space.', 'Rising Wing'),
  ('Quentin Grimes', 'Let the shot come naturally.', 'QG'),
  ('Quenton Jackson', 'Attack the opening.', 'Rising Guard'),
  ('Quinten Post', 'Size with a shooting touch.', 'Rising Big'),
  ('RJ Barrett', 'Attack with confidence.', 'RJ'),
  ('Rasheer Fleming', 'Length creates defensive possibilities.', 'Rising Forward'),
  ('RayJ Dennis', 'Control the pace.', 'Rising Guard'),
  ('Rayan Rupert', 'Defense gives potential a path.', 'Rising Wing'),
  ('Reed Sheppard', 'See the game before it happens.', 'The General'),
  ('Riley Minix', 'Keep building.', 'Rising Forward'),
  ('Rob Dillingham', 'Speed changes everything.', 'Dilly'),
  ('Robert Williams', 'Own the airspace.', 'Time Lord'),
  ('Rocco Zikarsky', 'The ceiling is literally enormous.', 'Rising Big'),
  ('Ron Harper Jr.', 'Build your own chapter.', 'Young Hawk'),
  ('Ron Holland', 'Pressure reveals competitors.', 'Rising Wing'),
  ('Royce O''Neale', 'Do the work that wins.', 'Royce'),
  ('Rudy Gobert', 'The paint has a guardian.', 'Stifle Tower'),
  ('Rui Hachimura', 'Strength and touch travel together.', 'Rui'),
  ('Russell Westbrook', 'Play every possession like it''s your last.', 'Brodie'),
  ('Ryan Dunn', 'Defense is the beginning.', 'Rising Stopper'),
  ('Ryan Kalkbrenner', 'Protect the rim with purpose.', 'Rising Big'),
  ('Ryan Nembhard', 'Vision turns into opportunity.', 'Rising Guard'),
  ('Ryan Rollins', 'The next level rewards patience.', 'Rising Guard'),
  ('Saddiq Bey', 'Stay ready for the clean look.', 'Saddiq'),
  ('Sam Hauser', 'One release can change a game.', 'The Sniper'),
  ('Sam Merrill', 'Never stop shooting.', 'The Marksman'),
  ('Sandro Mamukelashvili', 'Skill creates unexpected angles.', 'Mamu'),
  ('Santi Aldama', 'Modern size creates modern problems.', 'Santi'),
  ('Scoot Henderson', 'Speed meets ambition.', 'Scoot'),
  ('Scottie Barnes', 'Do a little of everything.', 'Scottie'),
  ('Scotty Pippen Jr.', 'Legacy gives you a starting line.', 'SPJ'),
  ('Sean Pedulla', 'The next opportunity is yours.', 'Rising Guard'),
  ('Seth Curry', 'The shot speaks for itself.', 'Chef''s Bloodline'),
  ('Shaedon Sharpe', 'The sky is still the limit.', 'Shae'),
  ('Shai Gilgeous-Alexander', 'Control the pace. Own the moment.', 'SGA'),
  ('Sharife Cooper', 'Quickness creates windows.', 'Rising Guard'),
  ('Sidy Cissoko', 'The tools are still developing.', 'Rising Wing'),
  ('Simone Fontecchio', 'Stay ready from deep.', 'The Italian Sniper'),
  ('Sion James', 'Defense makes opportunity.', 'Rising Wing'),
  ('Skal Labissière', 'The talent is still there.', 'Rising Big'),
  ('Spencer Jones', 'Keep the jumper ready.', 'Rising Wing'),
  ('Stanley Umude', 'Make every minute count.', 'Rising Wing'),
  ('Stephen Curry', 'Change the game. Then change it again.', 'Chef Curry'),
  ('Stephon Castle', 'The future starts with defense.', 'Rising Guard'),
  ('Steven Adams', 'Some problems are solved with strength.', 'Aquaman'),
  ('Svi Mykhailiuk', 'Leave no open shot unused.', 'Svi'),
  ('T.J. McConnell', 'Small guard. Huge impact.', 'T.J.'),
  ('Taelon Peter', 'The next chapter is unwritten.', 'Rising Prospect'),
  ('Taj Gibson', 'Experience never leaves the game.', 'Taj'),
  ('Tari Eason', 'Energy creates chaos.', 'The Pest'),
  ('Taurean Prince', 'Let the jumper travel.', 'TP'),
  ('Taylor Hendricks', 'Length gives the future shape.', 'Rising Forward'),
  ('Terance Mann', 'Do every job that matters.', 'T-Mann'),
  ('Terrence Shannon Jr.', 'Speed creates the advantage.', 'Rising Wing'),
  ('Thanasis Antetokounmpo', 'Bring the energy.', 'Thanasty'),
  ('Thomas Bryant', 'Big bodies finish plays.', 'TB'),
  ('Tidjane Salaün', 'Potential grows in silence.', 'Rising Forward'),
  ('Tim Hardaway Jr.', 'The jumper can heat up instantly.', 'Timmy'),
  ('Tobias Harris', 'Stay smooth under pressure.', 'Tobias'),
  ('Toby Okani', 'Keep building the complete game.', 'Rising Wing'),
  ('Tolu Smith', 'Own the interior.', 'Rising Big'),
  ('Tony Bradley', 'Size creates second chances.', 'Rising Big'),
  ('Tosan Evbuomwan', 'Versatility gives you a future.', 'Rising Forward'),
  ('Toumani Camara', 'Defense gives everything else a chance.', 'Rising Wing'),
  ('Trae Young', 'Range changes the rules.', 'Ice Trae'),
  ('Trayce Jackson-Davis', 'Finish every play above the rim.', 'TJD'),
  ('Tre Johnson', 'Pure scoring travels.', 'Rising Scorer'),
  ('Tre Jones', 'Keep the offense organized.', 'Baby Joe'),
  ('Tre Mann', 'Confidence creates freedom.', 'Tre'),
  ('Tre Scott', 'Stay ready for the opportunity.', 'Rising Wing'),
  ('Trendon Watford', 'Versatility keeps you on the floor.', 'Rising Forward'),
  ('Trentyn Flowers', 'The tools are there. The time is now.', 'Rising Wing'),
  ('Trevor Keels', 'Keep attacking the next level.', 'Rising Guard'),
  ('Trey Alexander', 'Make every possession matter.', 'Rising Guard'),
  ('Trey Jemison', 'Own your space inside.', 'Rising Big'),
  ('Trey Murphy III', 'Shooters change geometry.', 'Trey Murphy'),
  ('Tristan Da Silva', 'Smooth decisions create open space.', 'Rising Forward'),
  ('Tristan Enaruna', 'The next step starts with patience.', 'Rising Wing'),
  ('Tristan Vukcevic', 'Skill gives size another dimension.', 'Rising Big'),
  ('Tristen Newton', 'Make the right play.', 'Rising Guard'),
  ('Ty Jerome', 'Make the smart play.', 'Ty'),
  ('TyTy Washington Jr.', 'Keep building the confidence.', 'TyTy'),
  ('Tyler Burton', 'Earn the next opportunity.', 'Rising Wing'),
  ('Tyler Herro', 'Shot makers don''t fear the moment.', 'Herro'),
  ('Tyler Kolek', 'See the pass before it exists.', 'The Magician'),
  ('Tyler Smith', 'Keep turning tools into production.', 'Rising Forward'),
  ('Tyrese Martin', 'Stay ready on both ends.', 'Rising Wing'),
  ('Tyrese Maxey', 'Speed turns confidence into chaos.', 'The Franchise'),
  ('Tyrese Proctor', 'Control the game from the backcourt.', 'Rising Guard'),
  ('Tyson Etienne', 'Never hesitate.', 'Rising Scorer'),
  ('Tyus Jones', 'Take care of the game.', 'Tyus Stones'),
  ('VJ Edgecombe', 'Explosiveness creates the first advantage.', 'Rising Star'),
  ('Victor Wembanyama', 'The future learned how to block shots.', 'Wemby'),
  ('Vince Williams Jr.', 'Do everything that winning requires.', 'Rising Wing'),
  ('Vladislav Goldin', 'Size becomes dangerous when paired with touch.', 'Rising Big'),
  ('Vít Krejčí', 'Make every possession count.', 'Rising Guard'),
  ('Walker Kessler', 'Protect the house.', 'The Wall'),
  ('Walter Clayton', 'Big shots belong to fearless guards.', 'Rising Scorer'),
  ('Wendell Carter Jr.', 'Control the glass. Control the paint.', 'WCJ'),
  ('Wendell Moore Jr.', 'Patience creates opportunity.', 'Rising Wing'),
  ('Will Richard', 'Shooters always have a place.', 'Rising Shooter'),
  ('Will Riley', 'The future is already moving.', 'Rising Wing'),
  ('Xavier Tillman Sr.', 'Winning plays don''t need applause.', 'X'),
  ('Yang Hansen', 'The next generation is getting taller.', 'Rising Big'),
  ('Yanic Konan Niederhäuser', 'The tools are still developing.', 'Rising Big'),
  ('Yuki Kawamura', 'Speed and vision beat size.', 'Rising Guard'),
  ('Yves Missi', 'Athleticism changes the interior.', 'Rising Big'),
  ('Zaccharie Risacher', 'The future wears a smooth jumper.', 'Rising Star'),
  ('Zach Collins', 'Big men can create too.', 'Zach'),
  ('Zach Edey', 'Some advantages are seven feet tall.', 'The Tower'),
  ('Zach LaVine', 'Rise above the rim.', 'Flight 8'),
  ('Zeke Nnaji', 'Keep attacking the next level.', 'Rising Big'),
  ('Ziaire Williams', 'The next leap starts with confidence.', 'Rising Wing'),
  ('Zion Williamson', 'Power changes the laws of gravity.', 'Zion'),
  ('Zyon Pullin', 'Every level is another opportunity.', 'Rising Guard')
) AS v(player_name, quote, nickname)
WHERE lower(r.player_name) = lower(v.player_name);
