-- Migration: Create nba_player_rankings table
-- Core player ranking table. Stores computed scores for every ranking type
-- (overall, offense, defense, scoring, etc.) for every season/version.
-- Scores are pre-computed by the ranking engine and stored here for fast reads.
-- Rankings are IMMUTABLE once published — new algorithm runs create new versions.

CREATE TABLE IF NOT EXISTS public.nba_player_rankings (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,

  -- Player identity
  player_id UUID REFERENCES public.nba_players(id) ON DELETE SET NULL,
  player_name TEXT NOT NULL,
  position TEXT,
  age INTEGER,

  -- Season + ranking context
  season TEXT NOT NULL,               -- '2025-26' (historical) or '2026-27' (projection)
  ranking_type TEXT NOT NULL,         -- 'overall', 'offense', 'defense', 'scoring',
                                      --  'playmaking', 'rebounding', 'shooting',
                                      --  'two_way', 'young', 'breakout'
  ranking_version TEXT NOT NULL,      -- e.g., '2026-27-v1'

  -- Rank data
  rank INTEGER NOT NULL,
  score NUMERIC(5,2) NOT NULL,        -- normalized 0-100
  tier TEXT NOT NULL,                 -- 'Generational', 'Superstar', 'All-Star',
                                      --  'Star', 'High-Level Starter', 'Starter',
                                      --  'Rotation', 'Fringe'
  previous_rank INTEGER,              -- rank in prior season (same ranking_type)
  rank_change INTEGER,                -- positive = moved up, negative = moved down

  -- Team info (season-aware — historical and projected are SEPARATE)
  team TEXT,                          -- 2026-27 projected team (or 2025-26 actual for historical rankings)
  historical_team TEXT,               -- 2025-26 actual team
  projected_team TEXT,                -- 2026-27 projected/current team

  -- Publication control (countdown system)
  is_published BOOLEAN NOT NULL DEFAULT false,
  published_at TIMESTAMPTZ,

  -- Quality signals
  confidence NUMERIC(4,3),            -- 0.000-1.000
  is_new BOOLEAN NOT NULL DEFAULT false,      -- player without prior season ranking
  low_confidence BOOLEAN NOT NULL DEFAULT false, -- small sample / uncertain projection
  games_played INTEGER,
  minutes_per_game NUMERIC(4,1),

  -- Component scores (all 0-100, pre-computed by engine)
  offense_score NUMERIC(5,2),
  defense_score NUMERIC(5,2),
  scoring_score NUMERIC(5,2),
  playmaking_score NUMERIC(5,2),
  rebounding_score NUMERIC(5,2),
  shooting_score NUMERIC(5,2),
  two_way_score NUMERIC(5,2),
  availability_score NUMERIC(5,2),
  team_context_score NUMERIC(5,2),

  -- Projection-specific fields (null for historical rankings)
  age_adjustment NUMERIC(5,4),        -- small modifier applied to project score
  multi_season_weight JSONB,          -- e.g., {"2025-26": 0.60, "2024-25": 0.25}

  -- Explanation (generated by engine, stored for fast UI reads)
  explanation TEXT,
  strengths TEXT[],                   -- e.g., ['Elite Scorer', 'Shot Creator']
  weaknesses TEXT[],                  -- e.g., ['Below-Average Defender']
  outlook TEXT,                       -- 2026-27 outlook paragraph

  -- Power Profile Details
  signature TEXT,                     -- e.g., 'THE EXECUTOR'
  player_class TEXT,                  -- e.g., 'THE ENGINE'
  potential TEXT,                     -- 'HIGH', 'ELITE', 'STABLE', etc.
  ceiling TEXT,                       -- e.g., 'S - Elite'
  status TEXT,                        -- 'ASCENDING', 'STABLE', 'NEW', etc.

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Unique: one rank entry per player per season per ranking type per version
CREATE UNIQUE INDEX IF NOT EXISTS idx_player_rankings_unique
  ON public.nba_player_rankings (player_name, season, ranking_type, ranking_version);

-- Unique rank within each season/type/version (no two players can share rank 1)
CREATE UNIQUE INDEX IF NOT EXISTS idx_player_rankings_rank_unique
  ON public.nba_player_rankings (season, ranking_type, ranking_version, rank);

-- Fast reads for frontend
CREATE INDEX IF NOT EXISTS idx_player_rankings_season_type_rank
  ON public.nba_player_rankings (season, ranking_type, rank)
  WHERE is_published = true;

CREATE INDEX IF NOT EXISTS idx_player_rankings_player_id
  ON public.nba_player_rankings (player_id, season);

CREATE INDEX IF NOT EXISTS idx_player_rankings_version
  ON public.nba_player_rankings (ranking_version);

CREATE INDEX IF NOT EXISTS idx_player_rankings_published
  ON public.nba_player_rankings (season, ranking_type, is_published, rank);

-- Auto-update trigger
CREATE OR REPLACE FUNCTION public.nba_player_rankings_update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_nba_player_rankings_ts
  BEFORE UPDATE ON public.nba_player_rankings
  FOR EACH ROW EXECUTE FUNCTION public.nba_player_rankings_update_timestamp();

-- Ranking type check
ALTER TABLE public.nba_player_rankings
  ADD CONSTRAINT chk_player_ranking_type
  CHECK (ranking_type IN ('overall', 'offense', 'defense', 'scoring',
                          'playmaking', 'rebounding', 'shooting',
                          'two_way', 'young', 'breakout'));

-- Score range check
ALTER TABLE public.nba_player_rankings
  ADD CONSTRAINT chk_player_ranking_score
  CHECK (score >= 0 AND score <= 100);

-- Enable RLS
ALTER TABLE public.nba_player_rankings ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'nba_player_rankings'
      AND policyname = 'Player rankings are viewable by everyone.'
  ) THEN
    CREATE POLICY "Player rankings are viewable by everyone."
      ON public.nba_player_rankings FOR SELECT USING (true);
  END IF;
END $$;
